% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[top=25mm,left=25mm,right=25mm,bottom=25mm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Attention Markets in Religious Digital Media},
  pdfauthor={Sikic, Luka and Palic, Petra},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Attention Markets in Religious Digital Media}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Mapping the Croatian Catholic Digital Space}
\author{Sikic, Luka and Palic, Petra}
\date{2026-01-27}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\section*{Abstract}\label{abstract}
\addcontentsline{toc}{section}{Abstract}

This study applies the attention economics framework to analyze the
structure and dynamics of Croatian Catholic digital media, providing the
first systematic mapping of a national religious digital media
ecosystem. Drawing on the DigiKat database comprising over 600,000 posts
published between 2021 and 2024 across multiple platforms, we examine
attention distribution, actor stratification, emotional dynamics, and
temporal patterns. Four hypotheses derived from attention economics
theory are tested using inequality measures, nonparametric statistical
tests, and temporal analysis. Results confirm that attention follows
power law distributions with extreme concentration, institutional actors
experience significant disadvantages in engagement rates compared to
non-institutional communicators, emotional profiles differ significantly
across actor types, and the Catholic liturgical calendar structures
posting rhythms. These findings extend attention economics scholarship
to nonprofit religious communication contexts while providing baseline
measurements for the Croatian Catholic digital space. The DigiKat
database is introduced as a resource for future research on religious
digital communication.

\textbf{Keywords:} attention economics, religious communication, digital
media, Catholic Church, Croatia

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Introduction}\label{introduction}

The digital transformation of religious communication represents one of
the most significant shifts in how faith communities engage with their
publics. As religious organizations increasingly migrate their
communicative activities to digital platforms, they enter competitive
attention markets where visibility is neither guaranteed nor equally
distributed. This study applies the attention economics framework to
analyze the structure and dynamics of Croatian Catholic digital media,
providing the first systematic mapping of a national religious digital
media ecosystem.

Herbert Simon {[}-@simon1971{]} famously observed that information
abundance creates attention scarcity. In contemporary digital
environments, this insight has profound implications for religious
organizations that historically enjoyed privileged access to their
communities through established institutional channels. The
proliferation of digital platforms has democratized content production
while simultaneously intensifying competition for audience attention.
Religious communicators now compete not only with secular media but also
with entertainment, social networks, and an endless stream of digital
content vying for the same finite cognitive resources of potential
audiences.

Croatia presents a particularly compelling case for examining religious
digital communication. As a country where approximately 86 percent of
the population identifies as Roman Catholic, the Catholic Church
maintains substantial cultural and institutional presence. Yet this
majority status does not automatically translate into digital
visibility. The Croatian Catholic digital space encompasses diverse
actors ranging from official Church institutions and diocesan
communications offices to independent Catholic media outlets,
charismatic renewal movements, individual clergy, and lay influencers
operating devotional social media pages. How attention distributes
across this heterogeneous field of communicators remains an open
empirical question with significant implications for understanding
religious communication in the digital age.

This study addresses three interrelated research questions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  How is attention distributed across platforms and actors in the
  Croatian Catholic digital space?
\item
  Do institutional actors experience systematic disadvantages in
  capturing audience attention compared to grassroots and individual
  communicators?
\item
  What role do emotional content and temporal rhythms play in attention
  allocation within religious digital media?
\end{enumerate}

To address these questions, we analyze a comprehensive database of over
600,000 digital posts published between 2021 and 2024 across multiple
platforms including websites, Facebook, Instagram, YouTube, Twitter,
forums, and comment sections. This corpus, developed as part of the
DigiKat research project, represents the most extensive collection of
Croatian Catholic digital content assembled for scholarly analysis.
Beyond its empirical contributions, this study introduces the DigiKat
database as a resource for future research on religious digital
communication in Croatia and comparable contexts.

The analysis proceeds through four complementary dimensions. We first
examine the structural distribution of content and engagement across
platforms and actor types, measuring concentration through Gini
coefficients and testing for power law distributions characteristic of
attention markets. We then investigate the institutional attention gap
by comparing engagement rates between official Church communicators and
non-institutional actors. Subsequently, we analyze emotional dimensions
of attention capture through Facebook reaction data, examining how
different actor types elicit distinct emotional responses. Finally, we
explore temporal dynamics of attention, focusing on how the liturgical
calendar structures communicative rhythms in religious digital media.

Our findings contribute to attention economics scholarship by
demonstrating how its core predictions manifest in a nonprofit religious
media ecosystem, extending theoretical frameworks developed primarily in
commercial contexts. For scholars of digital religion, we provide
baseline measurements against which future changes can be assessed. For
Catholic communication practitioners, the results offer empirically
grounded insights into the attention landscape they navigate.

\section{Theoretical Framework}\label{theoretical-framework}

\subsection{Attention Scarcity in Digital
Environments}\label{attention-scarcity-in-digital-environments}

The attention economics paradigm emerged from recognition that
traditional economic models inadequately capture value creation and
exchange in information-rich environments. Simon {[}-@simon1971{]}
articulated the foundational insight when he noted that a wealth of
information creates a poverty of attention and a need to allocate that
attention efficiently among the overabundance of information sources
that might consume it. This observation has gained urgency as digital
technologies have exponentially increased information production while
human cognitive capacities remain fundamentally unchanged.

Goldhaber {[}-@goldhaber1997{]} extended this framework by proposing
attention itself as the primary currency of digital economies. Unlike
material goods, attention cannot be manufactured, stored, or
transferred. Each individual possesses a finite daily allocation of
attention that various actors compete to capture. Davenport and Beck
{[}-@davenport2001{]} formalized attention management as an
organizational imperative, demonstrating how institutions must
strategically compete for stakeholder attention in increasingly
cluttered information environments.

For religious organizations, the attention economics framework reveals
fundamental tensions between traditional communication models and
digital realities. Churches historically operated within what might be
termed attention-privileged environments where institutional authority
and community embeddedness guaranteed audience access. Sunday sermons
reached congregations without competition from alternative content
streams. Pastoral letters received attention by virtue of their source.
Digital platforms dissolve these structural advantages, forcing
religious communicators to compete for attention on equal footing with
secular content producers and algorithmic systems that optimize for
engagement rather than spiritual edification.

\subsection{Power Law Distributions in Attention
Markets}\label{power-law-distributions-in-attention-markets}

A consistent empirical finding across digital platforms is that
attention distributes according to power law rather than normal
distributions {[}@barabasi1999{]}. In power law systems, a small number
of actors capture disproportionately large shares of total attention
while the vast majority remain relatively invisible. This pattern,
sometimes described as winner-take-all dynamics, emerges from
preferential attachment mechanisms where already-visible actors attract
additional attention precisely because of their existing visibility.

Rieder et al. {[}-@rieder2020{]} documented extreme concentration in
their large-scale mapping of YouTube, finding that the top 0.4 percent
of channels accounted for 62 percent of total views. Webster
{[}-@webster2014{]} demonstrated similar patterns across diverse media
systems, arguing that audience attention naturally concentrates
regardless of the abundance of available content. The Gini coefficient,
borrowed from income inequality research, provides a standard measure of
such concentration, with values approaching 1.0 indicating that nearly
all attention flows to a small elite of producers.

These distributional patterns carry normative implications for religious
communication. If Catholic digital media exhibits extreme concentration,
questions arise about pluralism, voice diversity, and whether official
Church communications effectively reach intended audiences or are
drowned out by more attention-savvy competitors. Power law distributions
also suggest that investment in digital communication may yield highly
unequal returns, with most actors struggling to achieve visibility
regardless of content quality or communicative effort.

\subsection{Platform Effects on Attention
Allocation}\label{platform-effects-on-attention-allocation}

Digital platforms do not merely transmit content but actively shape
attention allocation through their technical architectures and
algorithmic systems {[}@vandijck2018{]}. Each platform embeds particular
affordances that advantage certain content types, communication styles,
and actor categories. Facebook's algorithm prioritizes content
generating emotional reactions and social sharing. Instagram rewards
visual aesthetics and consistent posting schedules. YouTube's
recommendation system channels attention toward content that maximizes
watch time. These platform logics create differential environments for
religious communicators depending on how well their content aligns with
algorithmically favored characteristics.

Platform effects manifest in what we term engagement efficiency, the
ratio between attention captured and content produced. Actors whose
content aligns with platform affordances achieve higher engagement per
post than those whose communication styles conflict with platform
logics. For religious institutions accustomed to formal, text-heavy
communication, platforms optimizing for emotional resonance and visual
appeal may present systematic disadvantages. Conversely, individual
clergy with authentic personal voices or charismatic communities
emphasizing emotional spiritual experience may find their communication
styles naturally aligned with platform incentives.

\subsection{Hypotheses}\label{hypotheses}

Drawing from attention economics theory, we derive four testable
hypotheses about the Croatian Catholic digital media space:

\textbf{Hypothesis 1 (Power Law Distribution):} Attention in the
Croatian Catholic digital space follows a power law distribution, with
engagement concentrated among a small elite of actors. Specifically, we
expect the log-log relationship between rank and engagement to exhibit
strong linearity (R² \textgreater{} 0.90) and the Gini coefficient to
exceed 0.80, indicating extreme inequality.

\textbf{Hypothesis 2 (Concentration Ratios):} The top 10 percent of
sources capture the majority of total engagement, consistent with
winner-take-all dynamics observed in other digital media ecosystems. We
operationalize this through concentration ratios, predicting CR10
exceeding 50 percent.

\textbf{Hypothesis 3 (Institutional Attention Gap):} Institutional
actors including official Church bodies, diocesan communications, and
academic institutions achieve lower engagement rates than
non-institutional actors such as individual clergy, charismatic
communities, and lay influencers. This reflects misalignment between
institutional communication styles and platform affordances optimizing
for personal authenticity and emotional resonance.

\textbf{Hypothesis 4 (Emotional Differentiation):} Actor types exhibit
significantly different emotional profiles in audience responses, with
devotional and charismatic content eliciting higher shares of affective
reactions (particularly LOVE) while institutional and news-oriented
content generates more distributed emotional responses including higher
ANGRY shares on controversial topics.

These hypotheses collectively test whether attention economics
principles developed in commercial media contexts apply to nonprofit
religious communication ecosystems, while the specific predictions allow
empirical assessment of how Catholic communicators fare in digital
attention markets.

\section{Data and Methods}\label{data-and-methods}

\subsection{The DigiKat Database}\label{the-digikat-database}

This study draws on the DigiKat database, a comprehensive collection of
Croatian Catholic digital content developed as part of a three-year
research project (2025-2027) investigating Catholic media representation
on Croatian internet portals and social networks. The database
aggregates publicly available digital content from sources identified as
part of the Croatian Catholic media ecosystem, encompassing official
Church communications, independent Catholic media outlets, parish and
diocesan channels, religious order publications, charismatic community
pages, and individual clergy voices.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n\_posts }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(dta)}
\NormalTok{n\_sources }\OtherTok{\textless{}{-}} \FunctionTok{uniqueN}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{FROM)}
\NormalTok{date\_min }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{DATE)}
\NormalTok{date\_max }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{DATE)}
\NormalTok{n\_platforms }\OtherTok{\textless{}{-}} \FunctionTok{uniqueN}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{SOURCE\_TYPE)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Database Overview:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Database Overview:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Total posts:"}\NormalTok{, }\FunctionTok{format}\NormalTok{(n\_posts, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Total posts: 372,944 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique sources:"}\NormalTok{, }\FunctionTok{format}\NormalTok{(n\_sources, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Unique sources: 9,896 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Date range:"}\NormalTok{, }\FunctionTok{as.character}\NormalTok{(date\_min), }\StringTok{"to"}\NormalTok{, }\FunctionTok{as.character}\NormalTok{(date\_max), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Date range: 2021-01-01 to 2024-12-31 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Platform types:"}\NormalTok{, n\_platforms, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Platform types: 8 
\end{verbatim}

The analytical corpus comprises 372,944 posts published between siječanj
01, 2021 and prosinac 31, 2024 across eight platform categories. Web
content constitutes the largest volume, followed by Facebook, Instagram,
YouTube, Twitter, forums, Reddit, and user comments on Catholic portals.
Each record contains metadata including source identifier, publication
date and time, platform type, post title, full text content, and
engagement metrics. For social media platforms, additional variables
capture platform-specific indicators such as follower counts, reach
estimates, and reaction breakdowns.

The database represents the most extensive collection of Croatian
Catholic digital content assembled for scholarly analysis. Unlike
studies focusing on single platforms or narrow time windows, DigiKat
enables cross-platform comparison and longitudinal analysis spanning
four complete calendar years. The database will be maintained and
updated throughout the project period, with anonymized subsets and
aggregated statistics made available to researchers following open
science principles.

\subsection{Data Collection}\label{data-collection}

Data collection employed multiple complementary methods adapted to
platform-specific technical constraints. Web content was gathered
through automated scraping of identified Catholic portals, news sites,
and organizational websites. Custom crawlers extracted article text,
metadata, and available engagement indicators at regular intervals
throughout the collection period.

Social media data collection utilized both official application
programming interfaces and specialized research tools. Facebook and
Instagram data were obtained through CrowdTangle, a Meta platform
providing access to public page content for academic research. YouTube
data were collected via the YouTube Data API, capturing video metadata,
view counts, and comment volumes. Twitter data were gathered through the
Academic Research API during its availability period, supplemented by
alternative collection methods following API access restrictions
implemented in 2023.

Forum content and user comments were collected through targeted scraping
of major Croatian discussion platforms and comment sections on Catholic
news portals. All collection procedures targeted only publicly
accessible content, excluding private groups, direct messages, or
content behind authentication barriers.

Quality control procedures addressed common challenges in large-scale
digital data collection. Duplicate detection algorithms identified and
removed repeated content across sources. Date parsing routines
standardized temporal information across platforms using different
timestamp formats. Text cleaning procedures removed HTML artifacts,
encoding errors, and platform-specific markup while preserving
substantive content.

\subsection{Actor Classification}\label{actor-classification}

To analyze attention distribution across different types of Catholic
communicators, we developed a hierarchical classification system
assigning each source to one of ten actor categories. The classification
employs a priority-based approach processing each source through
multiple identification layers.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# =============================================================================}
\CommentTok{\# ACTOR CLASSIFICATION v4}
\CommentTok{\# =============================================================================}
\CommentTok{\# Hierarchical priority system:}
\CommentTok{\# 1. Manual overrides for known high{-}visibility sources}
\CommentTok{\# 2. Secular media exclusions (100+ outlets)}
\CommentTok{\# 3. Domain{-}based classification for web sources}
\CommentTok{\# 4. Name pattern matching with word boundaries}
\CommentTok{\# 5. Platform{-}aware lay influencer detection}
\CommentTok{\# 6. Default to Other}
\CommentTok{\# =============================================================================}

\CommentTok{\# MANUAL OVERRIDES}
\NormalTok{manual\_overrides }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \StringTok{"Institutional Official"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"hrvatska katolička mreža"}\NormalTok{, }\StringTok{"hrvatska katolicka mreza"}\NormalTok{,}
    \StringTok{"informativna katolička agencija"}\NormalTok{, }\StringTok{"informativna katolicka agencija"}\NormalTok{,}
    \StringTok{"hrvatski katolički radio"}\NormalTok{, }\StringTok{"hrvatski katolicki radio"}\NormalTok{,}
    \StringTok{"hrvatska biskupska konferencija"}\NormalTok{, }\StringTok{"ika"}\NormalTok{, }\StringTok{"hkr"}\NormalTok{, }\StringTok{"hkm"}\NormalTok{, }\StringTok{"hbk"}\NormalTok{,}
    \StringTok{"tiskovni ured hbk"}\NormalTok{, }\StringTok{"radio marija"}
\NormalTok{  ),}
  \StringTok{"Independent Media"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"laudato tv"}\NormalTok{, }\StringTok{"laudatotv"}\NormalTok{, }\StringTok{"laudato.tv"}\NormalTok{, }\StringTok{"laudato.hr"}\NormalTok{, }\StringTok{"laudato"}\NormalTok{,}
    \StringTok{"bitno.net"}\NormalTok{, }\StringTok{"bitno net"}\NormalTok{, }\StringTok{"glas koncila"}\NormalTok{, }\StringTok{"glaskoncila"}\NormalTok{,}
    \StringTok{"nova eva"}\NormalTok{, }\StringTok{"nova{-}eva"}\NormalTok{, }\StringTok{"verbum"}\NormalTok{, }\StringTok{"totus tuus"}\NormalTok{, }\StringTok{"totus{-}tuus"}\NormalTok{,}
    \StringTok{"katolički tjednik"}\NormalTok{, }\StringTok{"katolicki tjednik"}\NormalTok{, }\StringTok{"kršćanska sadašnjost"}\NormalTok{,}
    \StringTok{"krscanska sadasnjost"}\NormalTok{, }\StringTok{"mir i dobro"}\NormalTok{, }\StringTok{"svjetlo riječi"}\NormalTok{,}
    \StringTok{"novizivot.net"}\NormalTok{, }\StringTok{"novi zivot"}\NormalTok{, }\StringTok{"novi život"}
\NormalTok{  ),}
  \StringTok{"Charismatic Communities"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"božja pobjeda"}\NormalTok{, }\StringTok{"bozja pobjeda"}\NormalTok{, }\StringTok{"bozjapobjeda"}\NormalTok{,}
    \StringTok{"muževni budite"}\NormalTok{, }\StringTok{"muzevni budite"}\NormalTok{, }\StringTok{"muzevnibudite"}\NormalTok{,}
    \StringTok{"srce isusovo"}\NormalTok{, }\StringTok{"srceisuovo"}\NormalTok{, }\StringTok{"cenacolo"}\NormalTok{, }\StringTok{"comunità cenacolo"}\NormalTok{,}
    \StringTok{"duhovna obnova"}\NormalTok{, }\StringTok{"molitvena snaga"}\NormalTok{,}
    \StringTok{"dom molitve slavonski brod"}\NormalTok{, }\StringTok{"dom molitve"}\NormalTok{,}
    \StringTok{"molitvena zajednica sv. josipa"}
\NormalTok{  ),}
  \StringTok{"Lay Influencers"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"katolička obitelj"}\NormalTok{, }\StringTok{"katolicka obitelj"}\NormalTok{,}
    \StringTok{"marija majka isusova"}\NormalTok{, }\StringTok{"božanske molitve"}\NormalTok{, }\StringTok{"bozanske molitve"}\NormalTok{,}
    \StringTok{"moćne molitve tv"}\NormalTok{, }\StringTok{"mocne molitve tv"}\NormalTok{, }\StringTok{"moćne molitve"}\NormalTok{, }\StringTok{"mocne molitve"}\NormalTok{,}
    \StringTok{"katoličke molitve"}\NormalTok{, }\StringTok{"katolicke molitve"}\NormalTok{,}
    \StringTok{"pulherissimus"}\NormalTok{, }\StringTok{"pod smokvom"}\NormalTok{,}
    \StringTok{"hrana za dušu"}\NormalTok{, }\StringTok{"hrana za dusu"}\NormalTok{,}
    \StringTok{"добровољци"}\NormalTok{, }\StringTok{"miletić marin"}\NormalTok{, }\StringTok{"miletic marin"}\NormalTok{,}
    \StringTok{"dijete vjere"}\NormalTok{, }\StringTok{"vjera"}\NormalTok{,}
    \StringTok{"kapljice ljubavi božje"}\NormalTok{, }\StringTok{"kapljice ljubavi bozje"}\NormalTok{,}
    \StringTok{"kršćanstvo"}\NormalTok{, }\StringTok{"krscanstvo"}\NormalTok{,}
    \StringTok{"jutarnja molitva duhu svetom"}\NormalTok{, }\StringTok{"blago molitve"}\NormalTok{,}
    \StringTok{"biblija krunice molitve"}\NormalTok{, }\StringTok{"molitve bogu"}\NormalTok{,}
    \StringTok{"vojnik sreće"}\NormalTok{, }\StringTok{"vojnik srece"}\NormalTok{, }\StringTok{"duhovne poruke i inspiracija"}\NormalTok{,}
    \StringTok{"kes duhovni kutak"}\NormalTok{, }\StringTok{"duhovni kutak"}\NormalTok{,}
    \StringTok{"molitve.hr"}\NormalTok{, }\StringTok{"duhovniportal.com"}\NormalTok{, }\StringTok{"duhovniportal"}
\NormalTok{  ),}
  \StringTok{"Diocesan"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"zagrebačka nadbiskupija"}\NormalTok{, }\StringTok{"zagrebacka nadbiskupija"}\NormalTok{,}
    \StringTok{"sisačka biskupija"}\NormalTok{, }\StringTok{"sisacka biskupija"}\NormalTok{,}
    \StringTok{"župa šurkovac"}\NormalTok{, }\StringTok{"zupa surkovac"}\NormalTok{, }\StringTok{"sveta mati slobode"}\NormalTok{,}
    \StringTok{"župa sv. ilije proroka metković"}\NormalTok{, }\StringTok{"zupa sv. ilije proroka metkovic"}\NormalTok{,}
    \StringTok{"župa uznesenja bdm"}\NormalTok{, }\StringTok{"zupa uznesenja bdm"}\NormalTok{, }\StringTok{"župa uznesenja bdm {-} stenjevec"}\NormalTok{,}
    \StringTok{"šibenska biskupija"}\NormalTok{, }\StringTok{"sibenska biskupija"}\NormalTok{,}
    \StringTok{"požeška biskupija"}\NormalTok{, }\StringTok{"pozeskа biskupija"}\NormalTok{,}
    \StringTok{"dubrovacka biskupija"}\NormalTok{, }\StringTok{"dubrovačka biskupija"}\NormalTok{,}
    \StringTok{"dubrovacka{-}biskupija.hr"}\NormalTok{,}
    \StringTok{"zupa tramosnica"}\NormalTok{, }\StringTok{"župa tramošnica"}\NormalTok{,}
    \StringTok{"župa sv. vida"}\NormalTok{, }\StringTok{"zupa sv. vida"}\NormalTok{, }\StringTok{"župa sv. vida {-} petruševec"}
\NormalTok{  ),}
  \StringTok{"Youth Organizations"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"susret hrvatske katoličke mladeži"}\NormalTok{, }\StringTok{"susret hrvatske katolicke mladezi"}\NormalTok{,}
    \StringTok{"shkm požega"}\NormalTok{, }\StringTok{"shkm pozega"}
\NormalTok{  ),}
  \StringTok{"Academic"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"hrvatsko katoličko sveučilište"}\NormalTok{, }\StringTok{"hrvatsko katolicko sveuciliste"}\NormalTok{,}
    \StringTok{"universitas studiorum catholica croatica"}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# SECULAR MEDIA EXCLUSIONS}
\NormalTok{secular\_exclusions }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \CommentTok{\# National portals}
  \StringTok{"slobodnadalmacija"}\NormalTok{, }\StringTok{"slobodnadalmacija.hr"}\NormalTok{, }
  \StringTok{"vecernji"}\NormalTok{, }\StringTok{"vecernji.hr"}\NormalTok{, }\StringTok{"index.hr"}\NormalTok{, }\StringTok{"index"}\NormalTok{,}
  \StringTok{"jutarnji"}\NormalTok{, }\StringTok{"jutarnji.hr"}\NormalTok{, }\StringTok{"novilist"}\NormalTok{, }\StringTok{"novilist.hr"}\NormalTok{,}
  \StringTok{"24sata"}\NormalTok{, }\StringTok{"24sata.hr"}\NormalTok{, }\StringTok{"direktno"}\NormalTok{, }\StringTok{"direktno.hr"}\NormalTok{,}
  \StringTok{"nacional"}\NormalTok{, }\StringTok{"nacional.hr"}\NormalTok{, }\StringTok{"tportal"}\NormalTok{, }\StringTok{"tportal.hr"}\NormalTok{,}
  \StringTok{"dnevnik.hr"}\NormalTok{, }\StringTok{"dnevnik"}\NormalTok{, }\StringTok{"hrt.hr"}\NormalTok{, }\StringTok{"hrt"}\NormalTok{, }
  \StringTok{"n1info"}\NormalTok{, }\StringTok{"n1info.hr"}\NormalTok{, }\StringTok{"n1"}\NormalTok{, }\StringTok{"rtl.hr"}\NormalTok{, }\StringTok{"rtl"}\NormalTok{, }\StringTok{"net.hr"}\NormalTok{, }
  \StringTok{"telegram.hr"}\NormalTok{, }\StringTok{"telegram"}\NormalTok{, }\StringTok{"story.hr"}\NormalTok{, }\StringTok{"express.hr"}\NormalTok{, }\StringTok{"express"}\NormalTok{, }\StringTok{"advance.hr"}\NormalTok{,}
  \CommentTok{\# Regional portals}
  \StringTok{"glasistre"}\NormalTok{, }\StringTok{"glasistre.hr"}\NormalTok{, }\StringTok{"dnevno.hr"}\NormalTok{, }\StringTok{"dnevno"}\NormalTok{, }
  \StringTok{"prigorski"}\NormalTok{, }\StringTok{"glas{-}slavonije"}\NormalTok{, }\StringTok{"glas slavonije"}\NormalTok{,}
  \StringTok{"croativ"}\NormalTok{, }\StringTok{"oluja.info"}\NormalTok{, }\StringTok{"maxportal"}\NormalTok{, }\StringTok{"maxportal.hr"}\NormalTok{,}
  \StringTok{"hkv.hr"}\NormalTok{, }\StringTok{"icv.hr"}\NormalTok{, }\StringTok{"novosti.hr"}\NormalTok{, }\StringTok{"7dnevno"}\NormalTok{, }\StringTok{"mnovine"}\NormalTok{, }
  \StringTok{"sjever.hr"}\NormalTok{, }\StringTok{"dulist.hr"}\NormalTok{, }\StringTok{"pozega.eu"}\NormalTok{, }\StringTok{"sibenik.in"}\NormalTok{,}
  \StringTok{"ferata.hr"}\NormalTok{, }\StringTok{"epodravina"}\NormalTok{, }\StringTok{"glasgacke"}\NormalTok{, }\StringTok{"radio{-}zlatar"}\NormalTok{, }
  \StringTok{"medjimurski.hr"}\NormalTok{, }\StringTok{"sbperiskop"}\NormalTok{, }\StringTok{"zagorje{-}international"}\NormalTok{,}
  \StringTok{"pozeski"}\NormalTok{, }\StringTok{"novine.hr"}\NormalTok{, }\StringTok{"dubrovnikinsider"}\NormalTok{, }\StringTok{"regionalni"}\NormalTok{, }
  \StringTok{"leportale"}\NormalTok{, }\StringTok{"varazdinske{-}vijesti"}\NormalTok{, }\StringTok{"radionasice"}\NormalTok{, }
  \StringTok{"brodportal"}\NormalTok{, }\StringTok{"ljportal"}\NormalTok{, }\StringTok{"dubrovnikportal"}\NormalTok{, }\StringTok{"01portal"}\NormalTok{,}
  \StringTok{"tomislavnews"}\NormalTok{, }\StringTok{"hia.com.hr"}\NormalTok{, }\StringTok{"portalnovosti"}\NormalTok{, }\StringTok{"antenazadar"}\NormalTok{,}
  \StringTok{"dalmacijanews"}\NormalTok{, }\StringTok{"zadarskilist"}\NormalTok{, }\StringTok{"medjimurjepress"}\NormalTok{, }
  \StringTok{"zagreb.info"}\NormalTok{, }\StringTok{"034portal"}\NormalTok{, }\StringTok{"057info"}\NormalTok{, }\StringTok{"cityportal"}\NormalTok{,}
  \StringTok{"klikaj.hr"}\NormalTok{, }\StringTok{"lika{-}online"}\NormalTok{, }\StringTok{"ploce.com"}\NormalTok{, }\StringTok{"sbonline"}\NormalTok{, }
  \StringTok{"narod.hr"}\NormalTok{, }\StringTok{"infokiosk"}\NormalTok{, }\StringTok{"hrsvijet"}\NormalTok{, }\StringTok{"tomislavcity"}\NormalTok{, }
  \StringTok{"vrisak.info"}\NormalTok{, }\StringTok{"dalmacijadanas"}\NormalTok{, }\StringTok{"dalmacijadanas.hr"}\NormalTok{,}
  \StringTok{"morski.hr"}\NormalTok{, }\StringTok{"zagreb.hr"}\NormalTok{, }\StringTok{"osijek031"}\NormalTok{, }\StringTok{"rijeka.hr"}\NormalTok{, }\StringTok{"zadar.hr"}\NormalTok{,}
  \StringTok{"zupanjac.net"}\NormalTok{, }\StringTok{"zupanjac"}\NormalTok{, }\StringTok{"dalmatinskiportal.hr"}\NormalTok{, }\StringTok{"dalmatinskiportal"}\NormalTok{,}
  \StringTok{"campaign{-}archive.com"}\NormalTok{,}
  \CommentTok{\# Forums and aggregators}
  \StringTok{"forum.hr"}\NormalTok{, }\StringTok{"reddit"}\NormalTok{, }\StringTok{"anonymous\_user"}\NormalTok{, }\StringTok{"komentari"}\NormalTok{, }\StringTok{"bug.hr"}\NormalTok{,}
  \CommentTok{\# Other}
  \StringTok{"inmemoriam"}\NormalTok{, }\StringTok{"magicus.info"}\NormalTok{, }\StringTok{"book.hr"}\NormalTok{, }\StringTok{"mojzagreb.info"}\NormalTok{, }
  \StringTok{"skole.hr"}\NormalTok{, }\StringTok{"tvprofil"}\NormalTok{, }\StringTok{"priznajem.hr"}\NormalTok{, }\StringTok{"dragovoljac.com"}\NormalTok{, }
  \StringTok{"croatia"}\NormalTok{, }\StringTok{"wikipedia"}\NormalTok{,}
  \StringTok{"facebook.com"}\NormalTok{, }\StringTok{"youtube.com"}\NormalTok{, }\StringTok{"instagram.com"}\NormalTok{, }\StringTok{"twitter.com"}\NormalTok{,}
  \CommentTok{\# Government}
  \StringTok{"županija"}\NormalTok{, }\StringTok{"zupanija"}\NormalTok{, }\StringTok{"grad "}\NormalTok{, }\StringTok{"opcina"}\NormalTok{, }\StringTok{"općina"}\NormalTok{,}
  \CommentTok{\# Non{-}Catholic religious}
  \StringTok{"kršćanska proročka crkva"}\NormalTok{, }\StringTok{"krscanska prorocka crkva"}\NormalTok{,}
  \StringTok{"crkva svemogućeg boga"}\NormalTok{, }\StringTok{"crkva svemoguceg boga"}\NormalTok{,}
  \StringTok{"jehovini svjedoci"}\NormalTok{, }\StringTok{"adventisti"}\NormalTok{, }\StringTok{"baptisti"}\NormalTok{, }\StringTok{"pentekostalna"}\NormalTok{,}
  \CommentTok{\# Political}
  \StringTok{"domovinski pokret"}\NormalTok{, }\StringTok{"hdz"}\NormalTok{, }\StringTok{"sdp"}\NormalTok{, }\StringTok{"most"}\NormalTok{, }\StringTok{"možemo"}\NormalTok{, }\StringTok{"mozemo"}
\NormalTok{)}

\CommentTok{\# DOMAIN PATTERNS}
\NormalTok{domain\_patterns }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \StringTok{"Institutional Official"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"hkm.hr"}\NormalTok{, }\StringTok{"ika.hkm.hr"}\NormalTok{, }\StringTok{"hkr.hkm.hr"}\NormalTok{, }\StringTok{"hbk.hr"}\NormalTok{, }\StringTok{"radiomarija.hr"}
\NormalTok{  ),}
  \StringTok{"Diocesan"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"zg{-}nadbiskupija.hr"}\NormalTok{, }\StringTok{"biskupija{-}varazdinska.hr"}\NormalTok{, }\StringTok{"djos.hr"}\NormalTok{,}
    \StringTok{"biskupija{-}sj.hr"}\NormalTok{, }\StringTok{"rzs.hr"}\NormalTok{, }\StringTok{"rkc{-}sisak.hr"}\NormalTok{, }\StringTok{"zadarskanadbiskupija.hr"}\NormalTok{,}
    \StringTok{"gospicko{-}senjska{-}biskupija.hr"}\NormalTok{, }\StringTok{"nadbiskupija{-}split.com"}\NormalTok{,}
    \StringTok{"nadbiskupija{-}split.hr"}\NormalTok{, }\StringTok{"dubrovacka{-}biskupija.hr"}\NormalTok{, }\StringTok{"porec{-}biskupija.hr"}\NormalTok{,}
    \StringTok{"biskupija{-}kk.hr"}\NormalTok{, }\StringTok{"rkc{-}pula.hr"}\NormalTok{, }\StringTok{"krizcevacka{-}eparhija.hr"}\NormalTok{,}
    \StringTok{"sibenska{-}biskupija.hr"}\NormalTok{, }\StringTok{"krizevci.hbk.hr"}
\NormalTok{  ),}
  \StringTok{"Independent Media"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"laudato.hr"}\NormalTok{, }\StringTok{"laudato.tv"}\NormalTok{, }\StringTok{"bitno.net"}\NormalTok{, }\StringTok{"glaskoncila.hr"}\NormalTok{,}
    \StringTok{"nova{-}eva.com"}\NormalTok{, }\StringTok{"verbum.hr"}\NormalTok{, }\StringTok{"ks.hr"}\NormalTok{, }\StringTok{"totus{-}tuus.hr"}\NormalTok{,}
    \StringTok{"svjetlorijeci.hr"}\NormalTok{, }\StringTok{"zivot.com.hr"}\NormalTok{, }\StringTok{"novizivot.net"}
\NormalTok{  ),}
  \StringTok{"Academic"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"unicath.hr"}\NormalTok{, }\StringTok{"hks.hr"}\NormalTok{, }\StringTok{"kbf.unizg.hr"}\NormalTok{, }\StringTok{"ffrz.hr"}\NormalTok{, }\StringTok{"hku.hr"}
\NormalTok{  ),}
  \StringTok{"Religious Orders"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"franjevci.hr"}\NormalTok{, }\StringTok{"franjevci{-}split.hr"}\NormalTok{, }\StringTok{"isusovci.hr"}\NormalTok{, }\StringTok{"dominikanci.hr"}\NormalTok{,}
    \StringTok{"kapucini.hr"}\NormalTok{, }\StringTok{"salezijanci.hr"}\NormalTok{, }\StringTok{"karmelicani.hr"}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# NAME PATTERNS}
\NormalTok{diocesan\_exact }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"zagrebačka nadbiskupija"}\NormalTok{, }\StringTok{"zagrebacka nadbiskupija"}\NormalTok{,}
  \StringTok{"splitsko{-}makarska nadbiskupija"}\NormalTok{, }\StringTok{"splitsko makarska"}\NormalTok{,}
  \StringTok{"đakovačko{-}osječka nadbiskupija"}\NormalTok{, }\StringTok{"djakovacko{-}osjecka"}\NormalTok{,}
  \StringTok{"riječka nadbiskupija"}\NormalTok{, }\StringTok{"rijecka nadbiskupija"}\NormalTok{,}
  \StringTok{"zadarska nadbiskupija"}\NormalTok{, }\StringTok{"sisačka biskupija"}\NormalTok{, }\StringTok{"sisacka biskupija"}\NormalTok{,}
  \StringTok{"varaždinska biskupija"}\NormalTok{, }\StringTok{"varazdinska biskupija"}\NormalTok{,}
  \StringTok{"križevačka eparhija"}\NormalTok{, }\StringTok{"krizevacka eparhija"}\NormalTok{,}
  \StringTok{"šibenska biskupija"}\NormalTok{, }\StringTok{"sibenska biskupija"}\NormalTok{,}
  \StringTok{"dubrovačka biskupija"}\NormalTok{, }\StringTok{"dubrovacka biskupija"}\NormalTok{,}
  \StringTok{"porečka i pulska biskupija"}\NormalTok{, }\StringTok{"porecka biskupija"}\NormalTok{,}
  \StringTok{"gospićko{-}senjska biskupija"}\NormalTok{, }\StringTok{"gospicko{-}senjska"}\NormalTok{,}
  \StringTok{"bjelovarsko{-}križevačka biskupija"}\NormalTok{, }\StringTok{"kotorska biskupija"}
\NormalTok{)}
\NormalTok{diocesan\_contains }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"nadbiskupija"}\NormalTok{, }\StringTok{"biskupija"}\NormalTok{, }\StringTok{"eparhija"}\NormalTok{, }\StringTok{"ordinarijat"}\NormalTok{)}

\NormalTok{orders\_exact }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"franjevci"}\NormalTok{, }\StringTok{"franjevci konventualci"}\NormalTok{, }\StringTok{"franjevci kapucini"}\NormalTok{,}
  \StringTok{"mala braća"}\NormalTok{, }\StringTok{"isusovci"}\NormalTok{, }\StringTok{"družba isusova"}\NormalTok{, }\StringTok{"druzba isusova"}\NormalTok{,}
  \StringTok{"dominikanci"}\NormalTok{, }\StringTok{"red propovjednika"}\NormalTok{, }\StringTok{"salezijanci"}\NormalTok{, }\StringTok{"don bosco"}\NormalTok{,}
  \StringTok{"karmelićani"}\NormalTok{, }\StringTok{"karmelicani"}\NormalTok{, }\StringTok{"karmel"}\NormalTok{, }\StringTok{"benediktinci"}\NormalTok{, }\StringTok{"benediktin"}\NormalTok{,}
  \StringTok{"kapucini"}\NormalTok{, }\StringTok{"pavlini"}\NormalTok{, }\StringTok{"trapisti"}\NormalTok{, }\StringTok{"cisterciti"}\NormalTok{, }\StringTok{"augustinci"}\NormalTok{,}
  \StringTok{"sestre milosrdnice"}\NormalTok{, }\StringTok{"uršulinke"}\NormalTok{, }\StringTok{"ursulinke"}\NormalTok{, }\StringTok{"klarise"}\NormalTok{,}
  \StringTok{"službenice milosrđa"}\NormalTok{, }\StringTok{"kćeri božje ljubavi"}\NormalTok{, }\StringTok{"školske sestre"}\NormalTok{,}
  \StringTok{"karmelićanke"}\NormalTok{, }\StringTok{"benediktinke"}\NormalTok{, }\StringTok{"dominikanke"}
\NormalTok{)}
\NormalTok{orders\_contains }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"franjevački"}\NormalTok{, }\StringTok{"franjevacki"}\NormalTok{, }\StringTok{"isusovački"}\NormalTok{, }\StringTok{"isusovacki"}\NormalTok{,}
  \StringTok{"dominikanski"}\NormalTok{, }\StringTok{"salezijanski"}\NormalTok{, }\StringTok{"karmelski"}\NormalTok{, }\StringTok{"benediktinski"}\NormalTok{,}
  \StringTok{"kapucinski"}\NormalTok{, }\StringTok{"pavlinski"}\NormalTok{, }\StringTok{"redovnici"}\NormalTok{, }\StringTok{"redovnice"}\NormalTok{,}
  \StringTok{"samostan"}\NormalTok{, }\StringTok{"provincija"}
\NormalTok{)}
\NormalTok{orders\_abbrev }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"ofm"}\NormalTok{, }\StringTok{"ofmcap"}\NormalTok{, }\StringTok{"ofmconv"}\NormalTok{, }\StringTok{"sj"}\NormalTok{, }\StringTok{"op"}\NormalTok{, }\StringTok{"sdb"}\NormalTok{,}
                   \StringTok{"ocd"}\NormalTok{, }\StringTok{"osb"}\NormalTok{, }\StringTok{"osbm"}\NormalTok{, }\StringTok{"cssr"}\NormalTok{, }\StringTok{"svd"}\NormalTok{, }\StringTok{"omc"}\NormalTok{)}

\NormalTok{charismatic\_exact }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"emmanuel"}\NormalTok{, }\StringTok{"taize"}\NormalTok{, }\StringTok{"taizé"}\NormalTok{, }\StringTok{"fokolari"}\NormalTok{, }\StringTok{"fokolarini"}\NormalTok{,}
  \StringTok{"kursiljo"}\NormalTok{, }\StringTok{"cursillo"}\NormalTok{, }\StringTok{"neokatekumenski put"}\NormalTok{, }\StringTok{"shalom"}\NormalTok{,}
  \StringTok{"zajednica beatitudes"}\NormalTok{, }\StringTok{"zajednica blaženstava"}\NormalTok{,}
  \StringTok{"dom molitve"}\NormalTok{, }\StringTok{"kuća molitve"}\NormalTok{, }\StringTok{"kuca molitve"}\NormalTok{,}
  \StringTok{"duhovna obnova"}\NormalTok{, }\StringTok{"molitvena snaga"}
\NormalTok{)}
\NormalTok{charismatic\_contains }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"molitvena zajednica"}\NormalTok{, }\StringTok{"karizmatska"}\NormalTok{, }\StringTok{"karizmatski"}\NormalTok{,}
  \StringTok{"neokatekumenski"}\NormalTok{, }\StringTok{"neokatekumenska"}\NormalTok{, }\StringTok{"obnova u duhu"}\NormalTok{,}
  \StringTok{"komunija i oslobođenje"}\NormalTok{, }\StringTok{"comunione e liberazione"}\NormalTok{,}
  \StringTok{"dom molitve"}\NormalTok{, }\StringTok{"house of prayer"}
\NormalTok{)}

\NormalTok{youth\_exact }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"frama"}\NormalTok{, }\StringTok{"shkm"}\NormalTok{, }\StringTok{"katolička mladež"}\NormalTok{, }\StringTok{"katolicka mladez"}\NormalTok{,}
  \StringTok{"mladi franjevci"}\NormalTok{, }\StringTok{"salezijanska mladež"}
\NormalTok{)}
\NormalTok{youth\_contains }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"ministranti"}\NormalTok{, }\StringTok{"mladifra"}\NormalTok{, }\StringTok{"kaem"}\NormalTok{, }\StringTok{"studentska kapelanija"}\NormalTok{,}
  \StringTok{"sveučilišna kapelanija"}\NormalTok{, }\StringTok{"sveuclisna kapelanija"}\NormalTok{,}
  \StringTok{"pastoral mladih"}\NormalTok{, }\StringTok{"mladi katolici"}
\NormalTok{)}

\NormalTok{academic\_exact }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"hrvatsko katoličko sveučilište"}\NormalTok{, }\StringTok{"hrvatsko katolicko sveuciliste"}\NormalTok{,}
  \StringTok{"katolički bogoslovni fakultet"}\NormalTok{, }\StringTok{"katolicki bogoslovni fakultet"}\NormalTok{,}
  \StringTok{"filozofski fakultet družbe isusove"}\NormalTok{, }\StringTok{"teologija u rijeci"}
\NormalTok{)}
\NormalTok{academic\_contains }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"teologija"}\NormalTok{, }\StringTok{"bogoslovija"}\NormalTok{, }\StringTok{"katehetski"}\NormalTok{)}
\NormalTok{academic\_abbrev }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"kbf"}\NormalTok{, }\StringTok{"hku"}\NormalTok{, }\StringTok{"ffrz"}\NormalTok{)}

\NormalTok{priest\_prefixes }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"fra "}\NormalTok{, }\StringTok{"don "}\NormalTok{, }\StringTok{"vlč. "}\NormalTok{, }\StringTok{"vlč."}\NormalTok{, }\StringTok{"vlc. "}\NormalTok{, }\StringTok{"vlc."}\NormalTok{,}
  \StringTok{"msgr. "}\NormalTok{, }\StringTok{"msgr."}\NormalTok{, }\StringTok{"mons. "}\NormalTok{, }\StringTok{"mons."}\NormalTok{,}
  \StringTok{"o. "}\NormalTok{, }\StringTok{"pater "}\NormalTok{, }\StringTok{"p. "}\NormalTok{, }\StringTok{"pr. "}\NormalTok{,}
  \StringTok{"s. "}\NormalTok{, }\StringTok{"sestra "}\NormalTok{, }\StringTok{"m. "}\NormalTok{, }\StringTok{"majka "}
\NormalTok{)}
\NormalTok{priest\_hierarchy }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"biskup "}\NormalTok{, }\StringTok{"nadbiskup "}\NormalTok{, }\StringTok{"kardinal "}\NormalTok{,}
  \StringTok{"mons. "}\NormalTok{, }\StringTok{"preč. "}\NormalTok{, }\StringTok{"prečasni "}
\NormalTok{)}
\NormalTok{priest\_contains }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"svećenik"}\NormalTok{, }\StringTok{"svecenik"}\NormalTok{, }\StringTok{"župnik"}\NormalTok{, }\StringTok{"zupnik"}\NormalTok{)}

\NormalTok{lay\_devotional }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"vjera"}\NormalTok{, }\StringTok{"molitva"}\NormalTok{, }\StringTok{"molitve"}\NormalTok{, }\StringTok{"isus"}\NormalTok{, }\StringTok{"krist"}\NormalTok{, }\StringTok{"gospa"}\NormalTok{, }\StringTok{"marija"}\NormalTok{,}
  \StringTok{"hrana za dušu"}\NormalTok{, }\StringTok{"hrana za dusu"}\NormalTok{, }\StringTok{"dijete vjere"}\NormalTok{,}
  \StringTok{"riječ dana"}\NormalTok{, }\StringTok{"rijec dana"}\NormalTok{, }\StringTok{"riječ božja"}\NormalTok{, }\StringTok{"rijec bozja"}\NormalTok{,}
  \StringTok{"sveti"}\NormalTok{, }\StringTok{"svetac"}\NormalTok{, }\StringTok{"svetica"}\NormalTok{, }\StringTok{"evanđelje"}\NormalTok{, }\StringTok{"evandelje"}\NormalTok{,}
  \StringTok{"duhovnost"}\NormalTok{, }\StringTok{"duhovna"}\NormalTok{, }\StringTok{"duhovni"}\NormalTok{, }\StringTok{"biblija"}\NormalTok{, }\StringTok{"biblijski"}\NormalTok{,}
  \StringTok{"psalm"}\NormalTok{, }\StringTok{"blagoslov"}\NormalTok{, }\StringTok{"krunica"}\NormalTok{, }\StringTok{"rozarij"}\NormalTok{, }\StringTok{"lectio divina"}\NormalTok{,}
  \StringTok{"katolička obitelj"}\NormalTok{, }\StringTok{"katolicka obitelj"}\NormalTok{, }\StringTok{"katolicki"}\NormalTok{,}
  \StringTok{"božanske"}\NormalTok{, }\StringTok{"bozanske"}\NormalTok{, }\StringTok{"moćne"}\NormalTok{, }\StringTok{"mocne"}
\NormalTok{)}
\NormalTok{lay\_exclude }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{".hr"}\NormalTok{, }\StringTok{".net"}\NormalTok{, }\StringTok{".com"}\NormalTok{, }\StringTok{"portal"}\NormalTok{, }\StringTok{"vijesti"}\NormalTok{,}
                 \StringTok{"news"}\NormalTok{, }\StringTok{"radio"}\NormalTok{, }\StringTok{"agencija"}\NormalTok{, }\StringTok{"tjednik"}\NormalTok{)}

\CommentTok{\# CLASSIFICATION FUNCTION}
\NormalTok{classify\_actor\_v4 }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(from\_val, }\AttributeTok{url\_val =} \ConstantTok{NA}\NormalTok{, }\AttributeTok{platform\_val =} \ConstantTok{NA}\NormalTok{) \{}
  
\NormalTok{  from\_lower }\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{trimws}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(from\_val)))}
\NormalTok{  url\_lower }\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(url\_val), }\StringTok{""}\NormalTok{, }\FunctionTok{as.character}\NormalTok{(url\_val)))}
\NormalTok{  platform\_lower }\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(platform\_val), }\StringTok{""}\NormalTok{, }\FunctionTok{as.character}\NormalTok{(platform\_val)))}
\NormalTok{  combined }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(from\_lower, url\_lower)}
  
\NormalTok{  match\_any }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(patterns, text, }\AttributeTok{fixed =} \ConstantTok{TRUE}\NormalTok{) \{}
    \FunctionTok{any}\NormalTok{(}\FunctionTok{sapply}\NormalTok{(patterns, }\ControlFlowTok{function}\NormalTok{(p) }\FunctionTok{grepl}\NormalTok{(p, text, }\AttributeTok{fixed =}\NormalTok{ fixed)))}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 1: Manual Overrides}
  \ControlFlowTok{for}\NormalTok{ (actor\_type }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(manual\_overrides)) \{}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(manual\_overrides[[actor\_type]], from\_lower)) \{}
      \FunctionTok{return}\NormalTok{(actor\_type)}
\NormalTok{    \}}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 2: Secular Media Exclusions}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(secular\_exclusions, combined)) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Other"}\NormalTok{)}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 3: Domain{-}based Classification}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nchar}\NormalTok{(url\_lower) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
    \ControlFlowTok{for}\NormalTok{ (actor\_type }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(domain\_patterns)) \{}
      \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(domain\_patterns[[actor\_type]], url\_lower)) \{}
        \FunctionTok{return}\NormalTok{(actor\_type)}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 4a: Diocesan}
\NormalTok{  is\_parish }\OtherTok{\textless{}{-}} \FunctionTok{grepl}\NormalTok{(}\StringTok{"\^{}župa|\^{}zupa|župi|zupi|{-} župa|{-} zupa"}\NormalTok{, from\_lower, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{||}
               \FunctionTok{grepl}\NormalTok{(}\StringTok{"parish"}\NormalTok{, from\_lower, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{)}
  
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(diocesan\_exact, from\_lower) }\SpecialCharTok{||}
      \FunctionTok{match\_any}\NormalTok{(diocesan\_contains, from\_lower) }\SpecialCharTok{||}
\NormalTok{      is\_parish) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Diocesan"}\NormalTok{)}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 4b: Religious Orders}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(orders\_exact, from\_lower) }\SpecialCharTok{||}
      \FunctionTok{match\_any}\NormalTok{(orders\_contains, from\_lower)) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Religious Orders"}\NormalTok{)}
\NormalTok{  \}}
  \ControlFlowTok{for}\NormalTok{ (abbr }\ControlFlowTok{in}\NormalTok{ orders\_abbrev) \{}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{grepl}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{b"}\NormalTok{, abbr, }\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{b"}\NormalTok{), from\_lower, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{)) \{}
      \FunctionTok{return}\NormalTok{(}\StringTok{"Religious Orders"}\NormalTok{)}
\NormalTok{    \}}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 4c: Charismatic Communities}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(charismatic\_exact, from\_lower) }\SpecialCharTok{||}
      \FunctionTok{match\_any}\NormalTok{(charismatic\_contains, from\_lower)) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Charismatic Communities"}\NormalTok{)}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 4d: Youth Organizations}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(youth\_exact, from\_lower) }\SpecialCharTok{||}
      \FunctionTok{match\_any}\NormalTok{(youth\_contains, from\_lower)) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Youth Organizations"}\NormalTok{)}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 4e: Academic}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(academic\_exact, from\_lower) }\SpecialCharTok{||}
      \FunctionTok{match\_any}\NormalTok{(academic\_contains, from\_lower)) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Academic"}\NormalTok{)}
\NormalTok{  \}}
  \ControlFlowTok{for}\NormalTok{ (abbr }\ControlFlowTok{in}\NormalTok{ academic\_abbrev) \{}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{grepl}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{b"}\NormalTok{, abbr, }\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{b"}\NormalTok{), from\_lower, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{)) \{}
      \FunctionTok{return}\NormalTok{(}\StringTok{"Academic"}\NormalTok{)}
\NormalTok{    \}}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 4f: Individual Priests}
  \ControlFlowTok{for}\NormalTok{ (prefix }\ControlFlowTok{in}\NormalTok{ priest\_prefixes) \{}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{startsWith}\NormalTok{(from\_lower, prefix)) }\FunctionTok{return}\NormalTok{(}\StringTok{"Individual Priests"}\NormalTok{)}
\NormalTok{  \}}
  \ControlFlowTok{for}\NormalTok{ (title }\ControlFlowTok{in}\NormalTok{ priest\_hierarchy) \{}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{startsWith}\NormalTok{(from\_lower, title)) }\FunctionTok{return}\NormalTok{(}\StringTok{"Individual Priests"}\NormalTok{)}
\NormalTok{  \}}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{match\_any}\NormalTok{(priest\_contains, from\_lower)) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Individual Priests"}\NormalTok{)}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 5: Lay Influencers}
\NormalTok{  has\_devotional }\OtherTok{\textless{}{-}} \FunctionTok{match\_any}\NormalTok{(lay\_devotional, from\_lower)}
\NormalTok{  has\_media\_indicator }\OtherTok{\textless{}{-}} \FunctionTok{match\_any}\NormalTok{(lay\_exclude, from\_lower)}
\NormalTok{  is\_likely\_social }\OtherTok{\textless{}{-}}\NormalTok{ platform\_lower }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"facebook"}\NormalTok{, }\StringTok{"instagram"}\NormalTok{, }\StringTok{"youtube"}\NormalTok{, }\StringTok{"twitter"}\NormalTok{) }\SpecialCharTok{||}
                      \SpecialCharTok{!}\FunctionTok{grepl}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.[a{-}z]\{2,4\}$"}\NormalTok{, from\_lower)}
  
  \ControlFlowTok{if}\NormalTok{ (has\_devotional }\SpecialCharTok{\&\&} \SpecialCharTok{!}\NormalTok{has\_media\_indicator }\SpecialCharTok{\&\&}\NormalTok{ is\_likely\_social) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Lay Influencers"}\NormalTok{)}
\NormalTok{  \}}
  
  \CommentTok{\# PRIORITY 6: Default}
  \FunctionTok{return}\NormalTok{(}\StringTok{"Other"}\NormalTok{)}
\NormalTok{\}}

\CommentTok{\# Apply classification}
\NormalTok{dta[, ACTOR\_TYPE }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{mapply}\NormalTok{(}
\NormalTok{  classify\_actor\_v4, }
\NormalTok{  FROM, }
  \ControlFlowTok{if}\NormalTok{ (}\StringTok{"URL"} \SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(dta)) URL }\ControlFlowTok{else} \ConstantTok{NA}\NormalTok{,}
\NormalTok{  SOURCE\_TYPE}
\NormalTok{)]}

\NormalTok{dta[, ACTOR\_TYPE }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{factor}\NormalTok{(ACTOR\_TYPE, }\AttributeTok{levels =} \FunctionTok{names}\NormalTok{(actor\_colors))]}
\end{Highlighting}
\end{Shaded}

The first layer applies manual overrides for known high-visibility
sources requiring explicit classification, including central Church
institutions such as the Croatian Bishops Conference (HBK), the Catholic
Information Agency (IKA), Croatian Catholic Radio (HKR), and major
independent media outlets. The second layer excludes secular media
sources covering religious topics, preventing misclassification of
mainstream news portals reporting on Catholic affairs.

Subsequent layers employ pattern matching against curated keyword lists.
Domain-based matching identifies sources through website URLs associated
with known Catholic organizations. Name-based matching captures sources
through distinctive terms including diocesan and parish identifiers,
religious order names, clerical titles, youth organization acronyms, and
academic institution references. A final layer identifies lay influencer
accounts through devotional keywords combined with social media platform
indicators.

The resulting ten categories comprise: \textbf{Institutional Official}
(central Church bodies), \textbf{Diocesan} (diocese and parish
communications), \textbf{Independent Media} (Catholic media outlets
operating independently of Church hierarchy), \textbf{Religious Orders}
(Franciscans, Jesuits, Dominicans, and other congregations),
\textbf{Charismatic Communities} (renewal movements and prayer
communities), \textbf{Individual Priests} (clergy identified by clerical
titles), \textbf{Youth Organizations} (FRAMA, SHKM, chaplaincies),
\textbf{Academic} (Catholic universities and theological faculties),
\textbf{Lay Influencers} (devotional social media pages operated by
laity), and \textbf{Other} (secular media, unidentified sources, general
discourse).

\subsection{Analytical Approach and Statistical
Tests}\label{analytical-approach-and-statistical-tests}

The analysis proceeds through four complementary dimensions
corresponding to our research questions and hypotheses.

\textbf{Market structure and concentration.} We assess attention
distribution using standard inequality measures from economics. The Gini
coefficient quantifies overall concentration, with values ranging from 0
(perfect equality) to 1 (complete concentration). Lorenz curves
visualize cumulative attention distribution across ranked sources.
Concentration ratios (CR5, CR10, CR20) measure the share of total
engagement captured by top-ranked actors. To test for power law
distribution, we fit linear regression models to log-transformed rank
and engagement values, with R² indicating goodness of fit and slope
coefficients characterizing concentration severity.

\textbf{Institutional attention gap.} We compare engagement rates
between institutional actors (Institutional Official, Diocesan,
Academic) and non-institutional actors (remaining categories). The
engagement rate normalizes interactions by follower count, enabling fair
comparison across accounts of different sizes. Given non-normal
distributions typical of social media metrics, we employ the Wilcoxon
rank-sum test for hypothesis testing. To examine differences across all
ten actor categories, we apply the Kruskal-Wallis test followed by Dunn
post-hoc comparisons with Bonferroni correction. Chi-square tests assess
association between actor types and platform preferences.

\textbf{Emotional attention capture.} For Facebook content, we analyze
reaction distributions (LOVE, WOW, HAHA, SAD, ANGRY) as indicators of
emotional response. We calculate reaction shares as proportions of total
emotional reactions and compare profiles across actor types using
Kruskal-Wallis tests. A Controversy Index combining angry reaction
intensity with visibility (calculated as ANGRY ratio multiplied by
log-transformed interactions) identifies content generating
disproportionate negative emotional response.

\textbf{Temporal dynamics.} We map posting activity onto the Catholic
liturgical calendar, categorizing dates into liturgical seasons (Advent,
Christmas, Ordinary Time, Lent, Easter) and major feast days. Effect
sizes quantify deviation from baseline activity during liturgically
significant periods. One-sample t-tests assess whether feast day effects
significantly differ from zero.

All analyses were conducted in R version 4.3 using the tidyverse
ecosystem for data manipulation, ggplot2 for visualization, and
specialized packages including ineq for inequality measures and
lubridate for date handling.

\section{Results}\label{results}

\subsection{Market Structure and
Concentration}\label{market-structure-and-concentration}

This section examines how attention distributes across platforms and
sources in the Croatian Catholic digital space, testing Hypotheses 1 and
2 regarding power law distributions and concentration.

\subsubsection{Platform Distribution}\label{platform-distribution}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{platform\_stats }\OtherTok{\textless{}{-}}\NormalTok{ dta[, .(}
  \AttributeTok{Posts =}\NormalTok{ .N,}
  \AttributeTok{Total\_Interactions =} \FunctionTok{sum}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Unique\_Sources =} \FunctionTok{uniqueN}\NormalTok{(FROM),}
  \AttributeTok{Mean\_Interactions =} \FunctionTok{mean}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ SOURCE\_TYPE][}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{Posts)]}

\NormalTok{platform\_stats[, }\StringTok{\textasciigrave{}}\AttributeTok{:=}\StringTok{\textasciigrave{}}\NormalTok{(}
  \AttributeTok{Volume\_Share =}\NormalTok{ Posts }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Posts) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
  \AttributeTok{Engagement\_Share =}\NormalTok{ Total\_Interactions }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Total\_Interactions) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
  \AttributeTok{Efficiency\_Index =}\NormalTok{ (Total\_Interactions }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Total\_Interactions)) }\SpecialCharTok{/}\NormalTok{ (Posts }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Posts))}
\NormalTok{)]}

\NormalTok{platform\_stats }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(SOURCE\_TYPE, Posts, Total\_Interactions, Unique\_Sources, Mean\_Interactions,}
\NormalTok{         Volume\_Share, Engagement\_Share, Efficiency\_Index) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Posts =} \FunctionTok{format}\NormalTok{(Posts, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Total\_Interactions =} \FunctionTok{format}\NormalTok{(Total\_Interactions, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Unique\_Sources =} \FunctionTok{format}\NormalTok{(Unique\_Sources, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Mean\_Interactions =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f"}\NormalTok{, Mean\_Interactions),}
    \AttributeTok{Volume\_Share =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, Volume\_Share),}
    \AttributeTok{Engagement\_Share =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, Engagement\_Share),}
    \AttributeTok{Efficiency\_Index =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f"}\NormalTok{, Efficiency\_Index)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Platform"}\NormalTok{, }\StringTok{"Posts"}\NormalTok{, }\StringTok{"Interactions"}\NormalTok{, }\StringTok{"Sources"}\NormalTok{, }
                      \StringTok{"Mean Int."}\NormalTok{, }\StringTok{"Volume \%"}\NormalTok{, }\StringTok{"Engagement \%"}\NormalTok{, }\StringTok{"Efficiency"}\NormalTok{),}
        \AttributeTok{caption =} \StringTok{"Table 1. Platform distribution of posts and engagement"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\DecValTok{7}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrrrrr}
\caption{\label{tab:platform-distribution}Table 1. Platform distribution of posts and engagement}\\
\toprule
Platform & Posts & Interactions & Sources & Mean Int. & Volume \% & Engagement \% & Efficiency\\
\midrule
web & 295,860 & 32,256,123 & 2,738 & 109.0 & 79.3\% & 79.1\% & 1.00\\
youtube & 38,267 & 4,946,542 & 2,838 & 133.1 & 10.3\% & 12.1\% & 1.18\\
facebook & 24,269 & 3,268,408 & 1,510 & 134.7 & 6.5\% & 8.0\% & 1.23\\
forum & 4,361 & 0 & 7 & NaN & 1.2\% & 0.0\% & 0.00\\
reddit & 3,857 & 0 & 1,319 & NaN & 1.0\% & 0.0\% & 0.00\\
\addlinespace
twitter & 3,211 & 28,532 & 1,536 & 8.9 & 0.9\% & 0.1\% & 0.08\\
comment & 1,989 & 0 & 23 & NaN & 0.5\% & 0.0\% & 0.00\\
instagram & 1,130 & 299,344 & 54 & 264.9 & 0.3\% & 0.7\% & 2.42\\
\bottomrule
\end{longtable}

Table 1 presents the distribution of content and engagement across
platforms. The efficiency index, calculated as the ratio of engagement
share to volume share, reveals substantial variation in platform
effectiveness. Values above 1.0 indicate platforms generating more
engagement than their content volume would predict, while values below
1.0 suggest underperformance relative to posting activity.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(platform\_stats, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(SOURCE\_TYPE, Efficiency\_Index), }
                           \AttributeTok{y =}\NormalTok{ Efficiency\_Index, }\AttributeTok{fill =}\NormalTok{ SOURCE\_TYPE)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{1}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f"}\NormalTok{, Efficiency\_Index)), }\AttributeTok{hjust =} \SpecialCharTok{{-}}\FloatTok{0.1}\NormalTok{, }\AttributeTok{size =} \FloatTok{3.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =}\NormalTok{ platform\_colors) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{limits =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{max}\NormalTok{(platform\_stats}\SpecialCharTok{$}\NormalTok{Efficiency\_Index) }\SpecialCharTok{*} \FloatTok{1.15}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Platform Engagement Efficiency"}\NormalTok{,}
    \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Efficiency Index"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{attention_markets_complete_2_files/figure-pdf/fig-platform-efficiency-1.pdf}}

}

\caption{\label{fig-platform-efficiency}Platform engagement efficiency.
The efficiency index represents the ratio of engagement share to volume
share, with values above 1.0 (red dashed line) indicating
overperformance relative to content volume.}

\end{figure}%

\subsubsection{Concentration Measures}\label{concentration-measures}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Aggregate by source}
\NormalTok{source\_stats }\OtherTok{\textless{}{-}}\NormalTok{ dta[, .(}
  \AttributeTok{Posts =}\NormalTok{ .N,}
  \AttributeTok{Total\_Interactions =} \FunctionTok{sum}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Actor\_Type =} \FunctionTok{first}\NormalTok{(ACTOR\_TYPE)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ FROM][}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{Total\_Interactions)]}

\NormalTok{source\_stats[, }\StringTok{\textasciigrave{}}\AttributeTok{:=}\StringTok{\textasciigrave{}}\NormalTok{(}
  \AttributeTok{Rank =}\NormalTok{ .I,}
  \AttributeTok{Cumulative\_Sources =}\NormalTok{ .I }\SpecialCharTok{/}\NormalTok{ .N }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
  \AttributeTok{Cumulative\_Interactions =} \FunctionTok{cumsum}\NormalTok{(Total\_Interactions) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Total\_Interactions) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{)]}

\NormalTok{total\_interactions }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats}\SpecialCharTok{$}\NormalTok{Total\_Interactions)}
\NormalTok{n\_sources\_total }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(source\_stats)}

\CommentTok{\# Concentration ratios}
\NormalTok{cr1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{1}\NormalTok{]}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{/}\NormalTok{ total\_interactions }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{cr5 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{]}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{/}\NormalTok{ total\_interactions }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{cr10 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{]}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{/}\NormalTok{ total\_interactions }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{cr20 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{20}\NormalTok{]}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{/}\NormalTok{ total\_interactions }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{cr50 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{50}\NormalTok{]}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{/}\NormalTok{ total\_interactions }\SpecialCharTok{*} \DecValTok{100}

\CommentTok{\# Top 10\% share}
\NormalTok{top\_10\_pct\_n }\OtherTok{\textless{}{-}} \FunctionTok{ceiling}\NormalTok{(n\_sources\_total }\SpecialCharTok{*} \FloatTok{0.10}\NormalTok{)}
\NormalTok{cr\_top10pct }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(source\_stats[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{top\_10\_pct\_n]}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{/}\NormalTok{ total\_interactions }\SpecialCharTok{*} \DecValTok{100}

\CommentTok{\# Gini coefficient}
\NormalTok{gini\_coef }\OtherTok{\textless{}{-}} \FunctionTok{ineq}\NormalTok{(source\_stats}\SpecialCharTok{$}\NormalTok{Total\_Interactions, }\AttributeTok{type =} \StringTok{"Gini"}\NormalTok{)}

\CommentTok{\# Power law regression}
\NormalTok{source\_positive }\OtherTok{\textless{}{-}}\NormalTok{ source\_stats[Total\_Interactions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{]}
\NormalTok{log\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{log10}\NormalTok{(Total\_Interactions) }\SpecialCharTok{\textasciitilde{}} \FunctionTok{log10}\NormalTok{(Rank), }\AttributeTok{data =}\NormalTok{ source\_positive)}
\NormalTok{slope }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(log\_model)[}\DecValTok{2}\NormalTok{]}
\NormalTok{r\_squared }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(log\_model)}\SpecialCharTok{$}\NormalTok{r.squared}

\FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"Gini Coefficient"}\NormalTok{, }\StringTok{"CR1 (Top source)"}\NormalTok{, }\StringTok{"CR5 (Top 5)"}\NormalTok{, }
             \StringTok{"CR10 (Top 10)"}\NormalTok{, }\StringTok{"CR20 (Top 20)"}\NormalTok{, }\StringTok{"CR50 (Top 50)"}\NormalTok{,}
             \StringTok{"Top 10\% of sources"}\NormalTok{, }\StringTok{"Power Law Slope"}\NormalTok{, }\StringTok{"Power Law R²"}\NormalTok{, }\StringTok{"Total Sources"}\NormalTok{),}
  \AttributeTok{Value =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.3f"}\NormalTok{, gini\_coef),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr1),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr5),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr10),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr20),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr50),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr\_top10pct),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f"}\NormalTok{, slope),}
    \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.3f"}\NormalTok{, r\_squared),}
    \FunctionTok{format}\NormalTok{(n\_sources\_total, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{)}
\NormalTok{  ),}
  \AttributeTok{Interpretation =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(gini\_coef }\SpecialCharTok{\textgreater{}} \FloatTok{0.8}\NormalTok{, }\StringTok{"Extreme inequality (H1 supported)"}\NormalTok{, }
           \FunctionTok{ifelse}\NormalTok{(gini\_coef }\SpecialCharTok{\textgreater{}} \FloatTok{0.6}\NormalTok{, }\StringTok{"High inequality"}\NormalTok{, }\StringTok{"Moderate inequality"}\NormalTok{)),}
    \StringTok{"Share of top source"}\NormalTok{,}
    \StringTok{"Share of top 5 sources"}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(cr10 }\SpecialCharTok{\textgreater{}} \DecValTok{50}\NormalTok{, }\StringTok{"H2 supported (\textgreater{}50\%)"}\NormalTok{, }\StringTok{"H2 not supported"}\NormalTok{),}
    \StringTok{"Share of top 20 sources"}\NormalTok{,}
    \StringTok{"Share of top 50 sources"}\NormalTok{,}
    \StringTok{"Share of top decile"}\NormalTok{,}
    \StringTok{"Power law steepness"}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(r\_squared }\SpecialCharTok{\textgreater{}} \FloatTok{0.9}\NormalTok{, }\StringTok{"Strong fit (H1 supported)"}\NormalTok{, }\StringTok{"Moderate fit"}\NormalTok{),}
    \StringTok{"Total unique sources"}
\NormalTok{  )}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Table 2. Concentration measures for attention distribution"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"l"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrl}
\caption{\label{tab:concentration-measures}Table 2. Concentration measures for attention distribution}\\
\toprule
Metric & Value & Interpretation\\
\midrule
Gini Coefficient & 0.980 & Extreme inequality (H1 supported)\\
CR1 (Top source) & 7.8\% & Share of top source\\
CR5 (Top 5) & 31.3\% & Share of top 5 sources\\
CR10 (Top 10) & 44.6\% & H2 not supported\\
CR20 (Top 20) & 56.5\% & Share of top 20 sources\\
\addlinespace
CR50 (Top 50) & 70.9\% & Share of top 50 sources\\
Top 10\% of sources & 98.3\% & Share of top decile\\
Power Law Slope & -2.65 & Power law steepness\\
Power Law R² & 0.912 & Strong fit (H1 supported)\\
Total Sources & 9,896 & Total unique sources\\
\bottomrule
\end{longtable}

Table 2 presents concentration measures testing Hypotheses 1 and 2. The
Gini coefficient of 0.980 indicates extreme inequality in attention
distribution. For comparison, this exceeds typical income inequality
measures in most developed countries.

The power law regression yields R² = 0.912, strongly supporting
Hypothesis 1. The concentration ratio CR10 of 44.6\% falls short of the
50\% threshold specified in Hypothesis 2.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(source\_stats, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Cumulative\_Sources, }\AttributeTok{y =}\NormalTok{ Cumulative\_Interactions)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"\#2c5f7c"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_ribbon}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =}\NormalTok{ Cumulative\_Sources, }\AttributeTok{ymax =}\NormalTok{ Cumulative\_Interactions), }
              \AttributeTok{fill =} \StringTok{"\#2c5f7c"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \DecValTok{70}\NormalTok{, }\AttributeTok{y =} \DecValTok{30}\NormalTok{, }
           \AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Gini = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(gini\_coef, }\DecValTok{3}\NormalTok{)), }
           \AttributeTok{size =} \DecValTok{5}\NormalTok{, }\AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \DecValTok{20}\NormalTok{, }\AttributeTok{y =} \DecValTok{80}\NormalTok{,}
           \AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Top 10\% of sources}\SpecialCharTok{\textbackslash{}n}\StringTok{capture "}\NormalTok{, }\FunctionTok{round}\NormalTok{(cr\_top10pct, }\DecValTok{1}\NormalTok{), }\StringTok{"\% of engagement"}\NormalTok{),}
           \AttributeTok{size =} \DecValTok{4}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{labels =} \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{paste0}\NormalTok{(x, }\StringTok{"\%"}\NormalTok{), }\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{100}\NormalTok{, }\DecValTok{20}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =} \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{paste0}\NormalTok{(x, }\StringTok{"\%"}\NormalTok{), }\AttributeTok{breaks =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{100}\NormalTok{, }\DecValTok{20}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Lorenz Curve of Engagement Inequality"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Cumulative \% of Sources (ranked by engagement)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Cumulative \% of Total Engagement"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{attention_markets_complete_2_files/figure-pdf/fig-lorenz-curve-1.pdf}}

}

\caption{\label{fig-lorenz-curve}Lorenz curve of engagement inequality.
The shaded area between the curve and the diagonal of equality
represents the degree of concentration. The Gini coefficient equals
twice this area.}

\end{figure}%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(source\_positive, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Rank, }\AttributeTok{y =}\NormalTok{ Total\_Interactions)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.3}\NormalTok{, }\AttributeTok{color =} \StringTok{"\#2c5f7c"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_log10}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_log10}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \DecValTok{10}\NormalTok{, }\AttributeTok{y =} \FunctionTok{min}\NormalTok{(source\_positive}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
           \AttributeTok{label =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Slope = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(slope, }\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{R² = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(r\_squared, }\DecValTok{3}\NormalTok{)),}
           \AttributeTok{hjust =} \DecValTok{0}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{, }\AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Rank{-}Engagement Distribution (Log{-}Log Scale)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Rank (log scale)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Total Interactions (log scale)"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{attention_markets_complete_2_files/figure-pdf/fig-power-law-1.pdf}}

}

\caption{\label{fig-power-law}Rank-engagement distribution on log-log
scale. Linear relationship confirms power law distribution consistent
with preferential attachment dynamics in attention markets.}

\end{figure}%

\subsubsection{Top Sources}\label{top-sources}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{source\_stats[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{] }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Share =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f\%\%"}\NormalTok{, Total\_Interactions }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(source\_stats}\SpecialCharTok{$}\NormalTok{Total\_Interactions) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{),}
    \AttributeTok{Cumulative =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, Cumulative\_Interactions),}
    \AttributeTok{Posts =} \FunctionTok{format}\NormalTok{(Posts, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Total\_Interactions =} \FunctionTok{format}\NormalTok{(Total\_Interactions, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(Rank, FROM, Actor\_Type, Posts, Total\_Interactions, Share, Cumulative) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Rank"}\NormalTok{, }\StringTok{"Source"}\NormalTok{, }\StringTok{"Actor Type"}\NormalTok{, }\StringTok{"Posts"}\NormalTok{, }\StringTok{"Interactions"}\NormalTok{, }\StringTok{"Share"}\NormalTok{, }\StringTok{"Cumulative"}\NormalTok{),}
        \AttributeTok{caption =} \StringTok{"Table 3. Top 10 sources by total engagement"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\StringTok{"l"}\NormalTok{, }\StringTok{"l"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{rllrrrr}
\caption{\label{tab:top-sources}Table 3. Top 10 sources by total engagement}\\
\toprule
Rank & Source & Actor Type & Posts & Interactions & Share & Cumulative\\
\midrule
1 & dnevno.hr & Other & 3,822 & 3,177,732 & 7.79\% & 7.8\%\\
2 & novizivot.net & Independent Media & 3,733 & 2,968,151 & 7.28\% & 15.1\%\\
3 & hkm.hr & Institutional Official & 43,809 & 2,908,877 & 7.13\% & 22.2\%\\
4 & index.hr & Other & 4,772 & 2,470,358 & 6.05\% & 28.2\%\\
5 & jutarnji.hr & Other & 5,143 & 1,246,230 & 3.05\% & 31.3\%\\
\addlinespace
6 & vecernji.hr & Other & 5,323 & 1,218,739 & 2.99\% & 34.3\%\\
7 & 24sata.hr & Other & 3,562 & 1,203,731 & 2.95\% & 37.2\%\\
8 & slobodnadalmacija.hr & Other & 6,871 & 1,088,602 & 2.67\% & 39.9\%\\
9 & pulherissimus & Lay Influencers & 4,231 & 1,068,219 & 2.62\% & 42.5\%\\
10 & telegram.hr & Other & 1,626 & 851,980 & 2.09\% & 44.6\%\\
\bottomrule
\end{longtable}

\subsection{Actor Stratification and Institutional
Gap}\label{actor-stratification-and-institutional-gap}

This section tests Hypothesis 3 regarding whether institutional actors
experience systematic disadvantages in attention capture compared to
non-institutional communicators.

\subsubsection{Actor Type Distribution}\label{actor-type-distribution}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{actor\_summary }\OtherTok{\textless{}{-}}\NormalTok{ dta[, .(}
  \AttributeTok{Sources =} \FunctionTok{uniqueN}\NormalTok{(FROM),}
  \AttributeTok{Posts =}\NormalTok{ .N,}
  \AttributeTok{Total\_Interactions =} \FunctionTok{sum}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Mean\_Interactions =} \FunctionTok{mean}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ ACTOR\_TYPE][}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{Total\_Interactions)]}

\NormalTok{total\_posts }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(actor\_summary}\SpecialCharTok{$}\NormalTok{Posts)}
\NormalTok{total\_int }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(actor\_summary}\SpecialCharTok{$}\NormalTok{Total\_Interactions)}

\NormalTok{actor\_summary[, }\StringTok{\textasciigrave{}}\AttributeTok{:=}\StringTok{\textasciigrave{}}\NormalTok{(}
  \AttributeTok{Post\_Share =}\NormalTok{ Posts }\SpecialCharTok{/}\NormalTok{ total\_posts }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
  \AttributeTok{Engagement\_Share =}\NormalTok{ Total\_Interactions }\SpecialCharTok{/}\NormalTok{ total\_int }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
  \AttributeTok{Efficiency =}\NormalTok{ (Total\_Interactions }\SpecialCharTok{/}\NormalTok{ total\_int) }\SpecialCharTok{/}\NormalTok{ (Posts }\SpecialCharTok{/}\NormalTok{ total\_posts)}
\NormalTok{)]}

\NormalTok{actor\_summary }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(ACTOR\_TYPE, Sources, Posts, Total\_Interactions, Mean\_Interactions,}
\NormalTok{         Post\_Share, Engagement\_Share, Efficiency) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Sources =} \FunctionTok{format}\NormalTok{(Sources, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Posts =} \FunctionTok{format}\NormalTok{(Posts, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Total\_Interactions =} \FunctionTok{format}\NormalTok{(Total\_Interactions, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Mean\_Interactions =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f"}\NormalTok{, Mean\_Interactions),}
    \AttributeTok{Post\_Share =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, Post\_Share),}
    \AttributeTok{Engagement\_Share =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, Engagement\_Share),}
    \AttributeTok{Efficiency =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f"}\NormalTok{, Efficiency)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Actor Type"}\NormalTok{, }\StringTok{"Sources"}\NormalTok{, }\StringTok{"Posts"}\NormalTok{, }\StringTok{"Interactions"}\NormalTok{, }
                      \StringTok{"Mean Int."}\NormalTok{, }\StringTok{"Post \%"}\NormalTok{, }\StringTok{"Engagement \%"}\NormalTok{, }\StringTok{"Efficiency"}\NormalTok{),}
        \AttributeTok{caption =} \StringTok{"Table 4. Content and engagement by actor type"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\DecValTok{7}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrrrrr}
\caption{\label{tab:actor-distribution}Table 4. Content and engagement by actor type}\\
\toprule
Actor Type & Sources & Posts & Interactions & Mean Int. & Post \% & Engagement \% & Efficiency\\
\midrule
Other & 9,629 & 273,204 & 28,547,015 & 108.9 & 73.3\% & 70.0\% & 0.96\\
Independent Media & 15 & 19,853 & 4,966,519 & 250.2 & 5.3\% & 12.2\% & 2.29\\
Lay Influencers & 45 & 17,615 & 3,573,939 & 206.0 & 4.7\% & 8.8\% & 1.85\\
Institutional Official & 141 & 49,335 & 3,141,583 & 63.7 & 13.2\% & 7.7\% & 0.58\\
Diocesan & 48 & 10,629 & 431,299 & 40.6 & 2.9\% & 1.1\% & 0.37\\
\addlinespace
Charismatic Communities & 11 & 564 & 98,580 & 182.2 & 0.2\% & 0.2\% & 1.60\\
Religious Orders & 12 & 1,291 & 29,714 & 23.0 & 0.3\% & 0.1\% & 0.21\\
Academic & 6 & 438 & 8,685 & 19.8 & 0.1\% & 0.0\% & 0.18\\
Youth Organizations & 3 & 15 & 1,615 & 107.7 & 0.0\% & 0.0\% & 0.98\\
\bottomrule
\end{longtable}

\subsubsection{Engagement Rate Analysis}\label{engagement-rate-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate engagement rate per source (normalized by followers where available)}
\NormalTok{source\_engagement }\OtherTok{\textless{}{-}}\NormalTok{ dta[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(FOLLOWERS\_COUNT) }\SpecialCharTok{\&}\NormalTok{ FOLLOWERS\_COUNT }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, .(}
  \AttributeTok{Posts =}\NormalTok{ .N,}
  \AttributeTok{Total\_Interactions =} \FunctionTok{sum}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Mean\_Followers =} \FunctionTok{mean}\NormalTok{(FOLLOWERS\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Engagement\_Rate =} \FunctionTok{sum}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{mean}\NormalTok{(FOLLOWERS\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{), by }\OtherTok{=}\NormalTok{ .(FROM, ACTOR\_TYPE)]}

\CommentTok{\# Group into institutional vs non{-}institutional}
\NormalTok{source\_engagement[, Institution\_Group }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{fifelse}\NormalTok{(}
\NormalTok{  ACTOR\_TYPE }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Institutional Official"}\NormalTok{, }\StringTok{"Diocesan"}\NormalTok{, }\StringTok{"Academic"}\NormalTok{),}
  \StringTok{"Institutional"}\NormalTok{,}
  \StringTok{"Non{-}Institutional"}
\NormalTok{)]}

\CommentTok{\# Summary by actor type}
\NormalTok{actor\_engagement }\OtherTok{\textless{}{-}}\NormalTok{ source\_engagement[, .(}
  \AttributeTok{N =}\NormalTok{ .N,}
  \AttributeTok{Mean\_Engagement\_Rate =} \FunctionTok{mean}\NormalTok{(Engagement\_Rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Median\_Engagement\_Rate =} \FunctionTok{median}\NormalTok{(Engagement\_Rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{SD =} \FunctionTok{sd}\NormalTok{(Engagement\_Rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ ACTOR\_TYPE][}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{Median\_Engagement\_Rate)]}

\NormalTok{actor\_engagement }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Mean\_Engagement\_Rate =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f\%\%"}\NormalTok{, Mean\_Engagement\_Rate),}
    \AttributeTok{Median\_Engagement\_Rate =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f\%\%"}\NormalTok{, Median\_Engagement\_Rate),}
    \AttributeTok{SD =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.2f"}\NormalTok{, SD)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Actor Type"}\NormalTok{, }\StringTok{"N Sources"}\NormalTok{, }\StringTok{"Mean Eng. Rate"}\NormalTok{, }
                      \StringTok{"Median Eng. Rate"}\NormalTok{, }\StringTok{"Std. Dev."}\NormalTok{),}
        \AttributeTok{caption =} \StringTok{"Table 5. Engagement rates by actor type (follower{-}normalized)"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\DecValTok{4}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrr}
\caption{\label{tab:engagement-rate-analysis}Table 5. Engagement rates by actor type (follower-normalized)}\\
\toprule
Actor Type & N Sources & Mean Eng. Rate & Median Eng. Rate & Std. Dev.\\
\midrule
Lay Influencers & 10 & 248.66\% & 263.84\% & 181.08\\
Diocesan & 5 & 341.09\% & 176.97\% & 315.20\\
Independent Media & 3 & 249.36\% & 133.62\% & 307.02\\
Academic & 1 & 65.74\% & 65.74\% & NA\\
Youth Organizations & 2 & 5.94\% & 5.94\% & 7.19\\
\addlinespace
Other & 2146 & 4.36\% & 0.49\% & 16.24\\
Institutional Official & 45 & 8.41\% & 0.29\% & 30.36\\
\bottomrule
\end{longtable}

\subsubsection{Statistical Tests}\label{statistical-tests}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Wilcoxon rank{-}sum test}
\NormalTok{wilcox\_result }\OtherTok{\textless{}{-}} \FunctionTok{wilcox.test}\NormalTok{(}
\NormalTok{  Engagement\_Rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Institution\_Group, }
  \AttributeTok{data =}\NormalTok{ source\_engagement,}
  \AttributeTok{alternative =} \StringTok{"two.sided"}
\NormalTok{)}

\CommentTok{\# Group statistics}
\NormalTok{group\_stats }\OtherTok{\textless{}{-}}\NormalTok{ source\_engagement[, .(}
  \AttributeTok{N =}\NormalTok{ .N,}
  \AttributeTok{Mean =} \FunctionTok{mean}\NormalTok{(Engagement\_Rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Median =} \FunctionTok{median}\NormalTok{(Engagement\_Rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{SD =} \FunctionTok{sd}\NormalTok{(Engagement\_Rate, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ Institution\_Group]}

\CommentTok{\# Kruskal{-}Wallis test}
\NormalTok{kw\_result }\OtherTok{\textless{}{-}} \FunctionTok{kruskal.test}\NormalTok{(Engagement\_Rate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ACTOR\_TYPE, }\AttributeTok{data =}\NormalTok{ source\_engagement)}

\CommentTok{\# Chi{-}square test for platform x actor association}
\NormalTok{platform\_actor\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{SOURCE\_TYPE, dta}\SpecialCharTok{$}\NormalTok{ACTOR\_TYPE)}
\NormalTok{chisq\_result }\OtherTok{\textless{}{-}} \FunctionTok{chisq.test}\NormalTok{(platform\_actor\_table)}

\CommentTok{\# Cramér\textquotesingle{}s V}
\NormalTok{n\_total }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(platform\_actor\_table)}
\NormalTok{cramers\_v }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(chisq\_result}\SpecialCharTok{$}\NormalTok{statistic }\SpecialCharTok{/}\NormalTok{ (n\_total }\SpecialCharTok{*}\NormalTok{ (}\FunctionTok{min}\NormalTok{(}\FunctionTok{dim}\NormalTok{(platform\_actor\_table)) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)))}

\FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Test =} \FunctionTok{c}\NormalTok{(}\StringTok{"Wilcoxon rank{-}sum"}\NormalTok{, }\StringTok{"Kruskal{-}Wallis"}\NormalTok{, }\StringTok{"Chi{-}square"}\NormalTok{),}
  \AttributeTok{Comparison =} \FunctionTok{c}\NormalTok{(}\StringTok{"Institutional vs Non{-}Institutional engagement rates"}\NormalTok{, }
                 \StringTok{"Engagement rates across all 10 actor types"}\NormalTok{, }
                 \StringTok{"Platform × Actor type association"}\NormalTok{),}
  \AttributeTok{Statistic =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{paste}\NormalTok{(}\StringTok{"W ="}\NormalTok{, }\FunctionTok{format}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{statistic, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{)),}
    \FunctionTok{paste}\NormalTok{(}\StringTok{"χ² ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(kw\_result}\SpecialCharTok{$}\NormalTok{statistic, }\DecValTok{2}\NormalTok{)),}
    \FunctionTok{paste}\NormalTok{(}\StringTok{"χ² ="}\NormalTok{, }\FunctionTok{format}\NormalTok{(}\FunctionTok{round}\NormalTok{(chisq\_result}\SpecialCharTok{$}\NormalTok{statistic, }\DecValTok{0}\NormalTok{), }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{))}
\NormalTok{  ),}
  \AttributeTok{df =} \FunctionTok{c}\NormalTok{(}\StringTok{"—"}\NormalTok{, kw\_result}\SpecialCharTok{$}\NormalTok{parameter, chisq\_result}\SpecialCharTok{$}\NormalTok{parameter),}
  \StringTok{\textasciigrave{}}\AttributeTok{p{-}value}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{format.pval}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{),}
    \FunctionTok{format.pval}\NormalTok{(kw\_result}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{),}
    \FunctionTok{format.pval}\NormalTok{(chisq\_result}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{)}
\NormalTok{  ),}
  \StringTok{\textasciigrave{}}\AttributeTok{Effect Size}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"—"}\NormalTok{,}
    \StringTok{"—"}\NormalTok{,}
    \FunctionTok{paste0}\NormalTok{(}\StringTok{"V = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(cramers\_v, }\DecValTok{3}\NormalTok{))}
\NormalTok{  ),}
  \AttributeTok{Result =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"H3 supported"}\NormalTok{, }\StringTok{"H3 not supported"}\NormalTok{),}
    \FunctionTok{ifelse}\NormalTok{(kw\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Significant"}\NormalTok{, }\StringTok{"Not significant"}\NormalTok{),}
    \FunctionTok{ifelse}\NormalTok{(chisq\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Significant"}\NormalTok{, }\StringTok{"Not significant"}\NormalTok{)}
\NormalTok{  )}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Table 6. Summary of statistical tests for actor stratification"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\StringTok{"l"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"l"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{llrrrrl}
\caption{\label{tab:statistical-tests}Table 6. Summary of statistical tests for actor stratification}\\
\toprule
Test & Comparison & Statistic & df & p-value & Effect Size & Result\\
\midrule
Wilcoxon rank-sum & Institutional vs Non-Institutional engagement rates & W = 62,500 & — & 0.1 & — & H3 not supported\\
Kruskal-Wallis & Engagement rates across all 10 actor types & χ² = 56.45 & 6 & 2.37e-10 & — & Significant\\
Chi-square & Platform × Actor type association & χ² = NaN & 63 & NA & V = NaN & NA\\
\bottomrule
\end{longtable}

The Wilcoxon rank-sum test reveals a non-significant difference in
engagement rates between institutional and non-institutional actors (W =
62,500, \emph{p} = 0.1), not supporting Hypothesis 3.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(source\_engagement[Engagement\_Rate }\SpecialCharTok{\textless{}} \FunctionTok{quantile}\NormalTok{(Engagement\_Rate, }\FloatTok{0.95}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)], }
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Institution\_Group, }\AttributeTok{y =}\NormalTok{ Engagement\_Rate, }\AttributeTok{fill =}\NormalTok{ Institution\_Group)) }\SpecialCharTok{+}
  \FunctionTok{geom\_violin}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.2}\NormalTok{, }\AttributeTok{fill =} \StringTok{"white"}\NormalTok{, }\AttributeTok{outlier.shape =} \ConstantTok{NA}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"point"}\NormalTok{, }\AttributeTok{shape =} \DecValTok{18}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Institutional"} \OtherTok{=} \StringTok{"\#1a3c5a"}\NormalTok{, }\StringTok{"Non{-}Institutional"} \OtherTok{=} \StringTok{"\#e07b39"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =} \ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{paste0}\NormalTok{(x, }\StringTok{"\%"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Institutional vs Non{-}Institutional Engagement Rates"}\NormalTok{,}
    \AttributeTok{subtitle =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Wilcoxon test: W = "}\NormalTok{, }\FunctionTok{format}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{statistic, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
                      \StringTok{", p "}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.001}\NormalTok{, }\StringTok{"\textless{} .001"}\NormalTok{, }
                                     \FunctionTok{paste0}\NormalTok{(}\StringTok{"= "}\NormalTok{, }\FunctionTok{round}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{3}\NormalTok{)))),}
    \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Engagement Rate (\%)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{attention_markets_complete_2_files/figure-pdf/fig-engagement-comparison-1.pdf}}

}

\caption{\label{fig-engagement-comparison}Engagement rate distributions
comparing institutional and non-institutional actors. Violin plots show
full distribution shape; embedded box plots indicate median and
interquartile range; red diamonds mark means. Top 5\% outliers excluded
for visualization clarity.}

\end{figure}%

\subsection{Emotional Attention
Capture}\label{emotional-attention-capture}

This section tests Hypothesis 4 regarding emotional differentiation
across actor types using Facebook reaction data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fb\_data }\OtherTok{\textless{}{-}}\NormalTok{ dta[SOURCE\_TYPE }\SpecialCharTok{==} \StringTok{"facebook"} \SpecialCharTok{\&} 
               \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(LOVE\_COUNT) }\SpecialCharTok{\&} 
               \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(INTERACTIONS) }\SpecialCharTok{\&} 
\NormalTok{               INTERACTIONS }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{]}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(fb\_data) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  fb\_data[, Total\_Reactions }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(LOVE\_COUNT), }\DecValTok{0}\NormalTok{, LOVE\_COUNT) }\SpecialCharTok{+} 
                               \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(WOW\_COUNT), }\DecValTok{0}\NormalTok{, WOW\_COUNT) }\SpecialCharTok{+} 
                               \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(HAHA\_COUNT), }\DecValTok{0}\NormalTok{, HAHA\_COUNT) }\SpecialCharTok{+} 
                               \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(SAD\_COUNT), }\DecValTok{0}\NormalTok{, SAD\_COUNT) }\SpecialCharTok{+} 
                               \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(ANGRY\_COUNT), }\DecValTok{0}\NormalTok{, ANGRY\_COUNT)]}
  
\NormalTok{  fb\_data[Total\_Reactions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\StringTok{\textasciigrave{}}\AttributeTok{:=}\StringTok{\textasciigrave{}}\NormalTok{(}
    \AttributeTok{LOVE\_SHARE =}\NormalTok{ LOVE\_COUNT }\SpecialCharTok{/}\NormalTok{ Total\_Reactions,}
    \AttributeTok{WOW\_SHARE =} \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(WOW\_COUNT), }\DecValTok{0}\NormalTok{, WOW\_COUNT) }\SpecialCharTok{/}\NormalTok{ Total\_Reactions,}
    \AttributeTok{HAHA\_SHARE =} \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(HAHA\_COUNT), }\DecValTok{0}\NormalTok{, HAHA\_COUNT) }\SpecialCharTok{/}\NormalTok{ Total\_Reactions,}
    \AttributeTok{SAD\_SHARE =} \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(SAD\_COUNT), }\DecValTok{0}\NormalTok{, SAD\_COUNT) }\SpecialCharTok{/}\NormalTok{ Total\_Reactions,}
    \AttributeTok{ANGRY\_SHARE =} \FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(ANGRY\_COUNT), }\DecValTok{0}\NormalTok{, ANGRY\_COUNT) }\SpecialCharTok{/}\NormalTok{ Total\_Reactions}
\NormalTok{  )]}
  
  \CommentTok{\# Controversy Index}
\NormalTok{  fb\_data[, Controversy\_Index }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ (}\FunctionTok{fifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(ANGRY\_COUNT), }\DecValTok{0}\NormalTok{, ANGRY\_COUNT) }\SpecialCharTok{/} 
\NormalTok{                                   (INTERACTIONS }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(INTERACTIONS }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)]}
  
\NormalTok{  controversy\_threshold }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{Controversy\_Index, }\FloatTok{0.95}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  fb\_data[, Is\_Controversial }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ Controversy\_Index }\SpecialCharTok{\textgreater{}}\NormalTok{ controversy\_threshold]}
\NormalTok{\}}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Facebook posts with reaction data:"}\NormalTok{, }\FunctionTok{format}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(fb\_data), }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Facebook posts with reaction data: 22,716 
\end{verbatim}

\subsubsection{Overall Emotional
Profile}\label{overall-emotional-profile}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(fb\_data) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  emotion\_totals }\OtherTok{\textless{}{-}} \FunctionTok{data.table}\NormalTok{(}
    \AttributeTok{Emotion =} \FunctionTok{c}\NormalTok{(}\StringTok{"LOVE"}\NormalTok{, }\StringTok{"WOW"}\NormalTok{, }\StringTok{"HAHA"}\NormalTok{, }\StringTok{"SAD"}\NormalTok{, }\StringTok{"ANGRY"}\NormalTok{),}
    \AttributeTok{Total =} \FunctionTok{c}\NormalTok{(}
      \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{LOVE\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
      \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{WOW\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
      \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{HAHA\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
      \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{SAD\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
      \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{ANGRY\_COUNT, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{    )}
\NormalTok{  )}
\NormalTok{  emotion\_totals[, Percentage }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ Total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Total) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{]}
  
\NormalTok{  emotion\_totals }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
      \AttributeTok{Total =} \FunctionTok{format}\NormalTok{(Total, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
      \AttributeTok{Percentage =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, Percentage)}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Reaction Type"}\NormalTok{, }\StringTok{"Total Count"}\NormalTok{, }\StringTok{"Share"}\NormalTok{),}
          \AttributeTok{caption =} \StringTok{"Table 7. Overall distribution of emotional reactions"}\NormalTok{,}
          \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrr}
\caption{\label{tab:emotion-overall}Table 7. Overall distribution of emotional reactions}\\
\toprule
Reaction Type & Total Count & Share\\
\midrule
LOVE & 2,988 & 41.0\%\\
WOW & 166 & 2.3\%\\
HAHA & 2,019 & 27.7\%\\
SAD & 920 & 12.6\%\\
ANGRY & 1,196 & 16.4\%\\
\bottomrule
\end{longtable}

\subsubsection{Emotional Profiles by Actor
Type}\label{emotional-profiles-by-actor-type}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(fb\_data) }\SpecialCharTok{\textgreater{}} \DecValTok{0} \SpecialCharTok{\&\&} \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{Total\_Reactions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  actor\_emotions }\OtherTok{\textless{}{-}}\NormalTok{ fb\_data[Total\_Reactions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, .(}
    \AttributeTok{N\_Posts =}\NormalTok{ .N,}
    \AttributeTok{LOVE =} \FunctionTok{mean}\NormalTok{(LOVE\_SHARE, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{WOW =} \FunctionTok{mean}\NormalTok{(WOW\_SHARE, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{HAHA =} \FunctionTok{mean}\NormalTok{(HAHA\_SHARE, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{SAD =} \FunctionTok{mean}\NormalTok{(SAD\_SHARE, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{ANGRY =} \FunctionTok{mean}\NormalTok{(ANGRY\_SHARE, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{  ), by }\OtherTok{=}\NormalTok{ ACTOR\_TYPE][}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{LOVE)]}
  
\NormalTok{  actor\_emotions }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
      \AttributeTok{N\_Posts =} \FunctionTok{format}\NormalTok{(N\_Posts, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
      \AttributeTok{LOVE =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, LOVE),}
      \AttributeTok{WOW =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, WOW),}
      \AttributeTok{HAHA =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, HAHA),}
      \AttributeTok{SAD =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, SAD),}
      \AttributeTok{ANGRY =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, ANGRY)}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Actor Type"}\NormalTok{, }\StringTok{"Posts"}\NormalTok{, }\StringTok{"LOVE"}\NormalTok{, }\StringTok{"WOW"}\NormalTok{, }\StringTok{"HAHA"}\NormalTok{, }\StringTok{"SAD"}\NormalTok{, }\StringTok{"ANGRY"}\NormalTok{),}
          \AttributeTok{caption =} \StringTok{"Table 8. Emotional profiles by actor type (mean share of reactions)"}\NormalTok{,}
          \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\DecValTok{5}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrrrr}
\caption{\label{tab:emotion-by-actor}Table 8. Emotional profiles by actor type (mean share of reactions)}\\
\toprule
Actor Type & Posts & LOVE & WOW & HAHA & SAD & ANGRY\\
\midrule
Academic & 1 & 100.0\% & 0.0\% & 0.0\% & 0.0\% & 0.0\%\\
Lay Influencers & 21 & 99.8\% & 0.0\% & 0.2\% & 0.0\% & 0.0\%\\
Diocesan & 8 & 75.1\% & 0.0\% & 0.0\% & 24.9\% & 0.0\%\\
Independent Media & 32 & 62.8\% & 2.0\% & 9.2\% & 20.5\% & 5.5\%\\
Other & 137 & 42.9\% & 2.7\% & 25.8\% & 12.9\% & 15.8\%\\
\addlinespace
Institutional Official & 2 & 0.0\% & 50.0\% & 16.7\% & 0.0\% & 33.3\%\\
\bottomrule
\end{longtable}

\subsubsection{Statistical Tests for Emotional
Differences}\label{statistical-tests-for-emotional-differences}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(fb\_data) }\SpecialCharTok{\textgreater{}} \DecValTok{0} \SpecialCharTok{\&\&} \FunctionTok{sum}\NormalTok{(fb\_data}\SpecialCharTok{$}\NormalTok{Total\_Reactions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  fb\_reactions }\OtherTok{\textless{}{-}}\NormalTok{ fb\_data[Total\_Reactions }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{]}
  
\NormalTok{  kw\_love }\OtherTok{\textless{}{-}} \FunctionTok{kruskal.test}\NormalTok{(LOVE\_SHARE }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ACTOR\_TYPE, }\AttributeTok{data =}\NormalTok{ fb\_reactions)}
\NormalTok{  kw\_angry }\OtherTok{\textless{}{-}} \FunctionTok{kruskal.test}\NormalTok{(ANGRY\_SHARE }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ACTOR\_TYPE, }\AttributeTok{data =}\NormalTok{ fb\_reactions)}
  
  \FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{Reaction =} \FunctionTok{c}\NormalTok{(}\StringTok{"LOVE"}\NormalTok{, }\StringTok{"ANGRY"}\NormalTok{),}
    \StringTok{\textasciigrave{}}\AttributeTok{Chi{-}squared}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\FunctionTok{round}\NormalTok{(kw\_love}\SpecialCharTok{$}\NormalTok{statistic, }\DecValTok{2}\NormalTok{), }\FunctionTok{round}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{statistic, }\DecValTok{2}\NormalTok{)),}
    \AttributeTok{df =} \FunctionTok{c}\NormalTok{(kw\_love}\SpecialCharTok{$}\NormalTok{parameter, kw\_angry}\SpecialCharTok{$}\NormalTok{parameter),}
    \StringTok{\textasciigrave{}}\AttributeTok{p{-}value}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\FunctionTok{format.pval}\NormalTok{(kw\_love}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{), }
                  \FunctionTok{format.pval}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{)),}
    \AttributeTok{Significant =} \FunctionTok{c}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(kw\_love}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Yes"}\NormalTok{, }\StringTok{"No"}\NormalTok{),}
                    \FunctionTok{ifelse}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Yes (H4)"}\NormalTok{, }\StringTok{"No"}\NormalTok{))}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Table 9. Kruskal{-}Wallis tests for emotional reaction differences across actor types"}\NormalTok{,}
          \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"r"}\NormalTok{, }\StringTok{"l"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrl}
\caption{\label{tab:emotion-tests}Table 9. Kruskal-Wallis tests for emotional reaction differences across actor types}\\
\toprule
Reaction & Chi-squared & df & p-value & Significant\\
\midrule
LOVE & 35.05 & 5 & 1.47e-06 & Yes\\
ANGRY & 25.43 & 5 & 0.000115 & Yes (H4)\\
\bottomrule
\end{longtable}

Both LOVE and ANGRY reaction shares differ significantly across actor
types (Kruskal-Wallis \emph{p} \textless{} .001 for both), supporting
Hypothesis 4 regarding emotional differentiation.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{exists}\NormalTok{(}\StringTok{"actor\_emotions"}\NormalTok{) }\SpecialCharTok{\&\&} \FunctionTok{nrow}\NormalTok{(actor\_emotions) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  actor\_emotions\_long }\OtherTok{\textless{}{-}}\NormalTok{ actor\_emotions }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(ACTOR\_TYPE, LOVE, WOW, HAHA, SAD, ANGRY) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(LOVE}\SpecialCharTok{:}\NormalTok{ANGRY, }\SpecialCharTok{\textasciitilde{}}\FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{gsub}\NormalTok{(}\StringTok{"\%"}\NormalTok{, }\StringTok{""}\NormalTok{, .)))) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols =}\NormalTok{ LOVE}\SpecialCharTok{:}\NormalTok{ANGRY, }\AttributeTok{names\_to =} \StringTok{"Emotion"}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{"Share"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Emotion =} \FunctionTok{factor}\NormalTok{(Emotion, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"LOVE"}\NormalTok{, }\StringTok{"WOW"}\NormalTok{, }\StringTok{"HAHA"}\NormalTok{, }\StringTok{"SAD"}\NormalTok{, }\StringTok{"ANGRY"}\NormalTok{)))}
  
  \FunctionTok{ggplot}\NormalTok{(actor\_emotions\_long, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Emotion, }\AttributeTok{y =}\NormalTok{ ACTOR\_TYPE, }\AttributeTok{fill =}\NormalTok{ Share)) }\SpecialCharTok{+}
    \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f"}\NormalTok{, Share)), }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_fill\_viridis\_c}\NormalTok{(}\AttributeTok{option =} \StringTok{"plasma"}\NormalTok{, }\AttributeTok{direction =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
      \AttributeTok{title =} \StringTok{"Emotional Profile Heatmap by Actor Type"}\NormalTok{,}
      \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{,}
      \AttributeTok{y =} \ConstantTok{NULL}\NormalTok{,}
      \AttributeTok{fill =} \StringTok{"Share \%"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{panel.grid =} \FunctionTok{element\_blank}\NormalTok{())}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{attention_markets_complete_2_files/figure-pdf/fig-emotion-heatmap-1.pdf}}

}

\caption{\label{fig-emotion-heatmap}Emotional profile heatmap by actor
type. Cell values represent mean percentage share of each reaction type
among all emotional reactions. Darker colors indicate higher shares.}

\end{figure}%

\subsection{Temporal Dynamics}\label{temporal-dynamics}

This section examines how the Catholic liturgical calendar structures
attention patterns in religious digital media.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dta[, DATE }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{as.Date}\NormalTok{(DATE)]}
\NormalTok{dta[, Year }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{year}\NormalTok{(DATE)]}
\NormalTok{dta[, Month }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{month}\NormalTok{(DATE)]}
\NormalTok{dta[, DOW }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{wday}\NormalTok{(DATE, }\AttributeTok{label =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{abbr =} \ConstantTok{FALSE}\NormalTok{)]}

\CommentTok{\# Easter calculation (Anonymous Gregorian algorithm)}
\NormalTok{calculate\_easter }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(year) \{}
\NormalTok{  a }\OtherTok{\textless{}{-}}\NormalTok{ year }\SpecialCharTok{\%\%} \DecValTok{19}
\NormalTok{  b }\OtherTok{\textless{}{-}}\NormalTok{ year }\SpecialCharTok{\%/\%} \DecValTok{100}
\NormalTok{  c }\OtherTok{\textless{}{-}}\NormalTok{ year }\SpecialCharTok{\%\%} \DecValTok{100}
\NormalTok{  d }\OtherTok{\textless{}{-}}\NormalTok{ b }\SpecialCharTok{\%/\%} \DecValTok{4}
\NormalTok{  e }\OtherTok{\textless{}{-}}\NormalTok{ b }\SpecialCharTok{\%\%} \DecValTok{4}
\NormalTok{  f }\OtherTok{\textless{}{-}}\NormalTok{ (b }\SpecialCharTok{+} \DecValTok{8}\NormalTok{) }\SpecialCharTok{\%/\%} \DecValTok{25}
\NormalTok{  g }\OtherTok{\textless{}{-}}\NormalTok{ (b }\SpecialCharTok{{-}}\NormalTok{ f }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%/\%} \DecValTok{3}
\NormalTok{  h }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{19} \SpecialCharTok{*}\NormalTok{ a }\SpecialCharTok{+}\NormalTok{ b }\SpecialCharTok{{-}}\NormalTok{ d }\SpecialCharTok{{-}}\NormalTok{ g }\SpecialCharTok{+} \DecValTok{15}\NormalTok{) }\SpecialCharTok{\%\%} \DecValTok{30}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ c }\SpecialCharTok{\%/\%} \DecValTok{4}
\NormalTok{  k }\OtherTok{\textless{}{-}}\NormalTok{ c }\SpecialCharTok{\%\%} \DecValTok{4}
\NormalTok{  l }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{32} \SpecialCharTok{+} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ e }\SpecialCharTok{+} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ i }\SpecialCharTok{{-}}\NormalTok{ h }\SpecialCharTok{{-}}\NormalTok{ k) }\SpecialCharTok{\%\%} \DecValTok{7}
\NormalTok{  m }\OtherTok{\textless{}{-}}\NormalTok{ (a }\SpecialCharTok{+} \DecValTok{11} \SpecialCharTok{*}\NormalTok{ h }\SpecialCharTok{+} \DecValTok{22} \SpecialCharTok{*}\NormalTok{ l) }\SpecialCharTok{\%/\%} \DecValTok{451}
\NormalTok{  month }\OtherTok{\textless{}{-}}\NormalTok{ (h }\SpecialCharTok{+}\NormalTok{ l }\SpecialCharTok{{-}} \DecValTok{7} \SpecialCharTok{*}\NormalTok{ m }\SpecialCharTok{+} \DecValTok{114}\NormalTok{) }\SpecialCharTok{\%/\%} \DecValTok{31}
\NormalTok{  day }\OtherTok{\textless{}{-}}\NormalTok{ ((h }\SpecialCharTok{+}\NormalTok{ l }\SpecialCharTok{{-}} \DecValTok{7} \SpecialCharTok{*}\NormalTok{ m }\SpecialCharTok{+} \DecValTok{114}\NormalTok{) }\SpecialCharTok{\%\%} \DecValTok{31}\NormalTok{) }\SpecialCharTok{+} \DecValTok{1}
  \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, month, day, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{))}
\NormalTok{\}}

\CommentTok{\# Liturgical season assignment}
\NormalTok{assign\_liturgical\_season }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(date) \{}
\NormalTok{  year }\OtherTok{\textless{}{-}} \FunctionTok{year}\NormalTok{(date)}
\NormalTok{  easter }\OtherTok{\textless{}{-}} \FunctionTok{calculate\_easter}\NormalTok{(year)}
  
\NormalTok{  ash\_wednesday }\OtherTok{\textless{}{-}}\NormalTok{ easter }\SpecialCharTok{{-}} \DecValTok{46}
\NormalTok{  pentecost }\OtherTok{\textless{}{-}}\NormalTok{ easter }\SpecialCharTok{+} \DecValTok{49}
  
\NormalTok{  advent\_start }\OtherTok{\textless{}{-}} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\StringTok{"11"}\NormalTok{, }\StringTok{"27"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{))}
\NormalTok{  advent\_start }\OtherTok{\textless{}{-}}\NormalTok{ advent\_start }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{7} \SpecialCharTok{{-}}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{wday}\NormalTok{(advent\_start) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\%} \DecValTok{7}
  \ControlFlowTok{if}\NormalTok{ (advent\_start }\SpecialCharTok{\textgreater{}} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\StringTok{"12"}\NormalTok{, }\StringTok{"03"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{))) \{}
\NormalTok{    advent\_start }\OtherTok{\textless{}{-}}\NormalTok{ advent\_start }\SpecialCharTok{{-}} \DecValTok{7}
\NormalTok{  \}}
  
\NormalTok{  christmas }\OtherTok{\textless{}{-}} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\StringTok{"12"}\NormalTok{, }\StringTok{"25"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{))}
\NormalTok{  prev\_epiphany }\OtherTok{\textless{}{-}} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\StringTok{"01"}\NormalTok{, }\StringTok{"06"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{))}
  
  \ControlFlowTok{if}\NormalTok{ (date }\SpecialCharTok{\textgreater{}=}\NormalTok{ advent\_start) \{}
    \ControlFlowTok{if}\NormalTok{ (date }\SpecialCharTok{\textless{}}\NormalTok{ christmas) }\FunctionTok{return}\NormalTok{(}\StringTok{"Advent"}\NormalTok{)}
    \ControlFlowTok{else} \FunctionTok{return}\NormalTok{(}\StringTok{"Christmas"}\NormalTok{)}
\NormalTok{  \}}
  
  \ControlFlowTok{if}\NormalTok{ (date }\SpecialCharTok{\textless{}}\NormalTok{ prev\_epiphany }\SpecialCharTok{+} \DecValTok{8} \SpecialCharTok{\&\&} \FunctionTok{month}\NormalTok{(date) }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\&\&} \FunctionTok{day}\NormalTok{(date) }\SpecialCharTok{\textless{}=} \DecValTok{13}\NormalTok{) \{}
    \FunctionTok{return}\NormalTok{(}\StringTok{"Christmas"}\NormalTok{)}
\NormalTok{  \}}
  
  \ControlFlowTok{if}\NormalTok{ (date }\SpecialCharTok{\textgreater{}=}\NormalTok{ ash\_wednesday }\SpecialCharTok{\&\&}\NormalTok{ date }\SpecialCharTok{\textless{}}\NormalTok{ easter) }\FunctionTok{return}\NormalTok{(}\StringTok{"Lent"}\NormalTok{)}
  \ControlFlowTok{if}\NormalTok{ (date }\SpecialCharTok{\textgreater{}=}\NormalTok{ easter }\SpecialCharTok{\&\&}\NormalTok{ date }\SpecialCharTok{\textless{}}\NormalTok{ pentecost) }\FunctionTok{return}\NormalTok{(}\StringTok{"Easter"}\NormalTok{)}
  
  \FunctionTok{return}\NormalTok{(}\StringTok{"Ordinary Time"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{dta[, Liturgical\_Season }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{sapply}\NormalTok{(DATE, assign\_liturgical\_season)]}
\end{Highlighting}
\end{Shaded}

\subsubsection{Liturgical Season
Analysis}\label{liturgical-season-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{season\_stats }\OtherTok{\textless{}{-}}\NormalTok{ dta[, .(}
  \AttributeTok{Posts =}\NormalTok{ .N,}
  \AttributeTok{Total\_Interactions =} \FunctionTok{sum}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Mean\_Interactions =} \FunctionTok{mean}\NormalTok{(INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Days =} \FunctionTok{uniqueN}\NormalTok{(DATE)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ Liturgical\_Season]}

\NormalTok{season\_stats[, }\StringTok{\textasciigrave{}}\AttributeTok{:=}\StringTok{\textasciigrave{}}\NormalTok{(}
  \AttributeTok{Posts\_Per\_Day =}\NormalTok{ Posts }\SpecialCharTok{/}\NormalTok{ Days,}
  \AttributeTok{Interactions\_Per\_Day =}\NormalTok{ Total\_Interactions }\SpecialCharTok{/}\NormalTok{ Days}
\NormalTok{)]}

\NormalTok{baseline\_ppd }\OtherTok{\textless{}{-}}\NormalTok{ season\_stats[Liturgical\_Season }\SpecialCharTok{==} \StringTok{"Ordinary Time"}\NormalTok{]}\SpecialCharTok{$}\NormalTok{Posts\_Per\_Day}
\NormalTok{season\_stats[, Effect\_Size }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ (Posts\_Per\_Day }\SpecialCharTok{{-}}\NormalTok{ baseline\_ppd) }\SpecialCharTok{/}\NormalTok{ baseline\_ppd }\SpecialCharTok{*} \DecValTok{100}\NormalTok{]}

\NormalTok{season\_order }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Advent"}\NormalTok{, }\StringTok{"Christmas"}\NormalTok{, }\StringTok{"Lent"}\NormalTok{, }\StringTok{"Easter"}\NormalTok{, }\StringTok{"Ordinary Time"}\NormalTok{)}
\NormalTok{season\_stats[, Liturgical\_Season }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{factor}\NormalTok{(Liturgical\_Season, }\AttributeTok{levels =}\NormalTok{ season\_order)]}

\NormalTok{season\_stats[}\FunctionTok{order}\NormalTok{(Liturgical\_Season)] }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Posts =} \FunctionTok{format}\NormalTok{(Posts, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Total\_Interactions =} \FunctionTok{format}\NormalTok{(Total\_Interactions, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{),}
    \AttributeTok{Mean\_Interactions =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f"}\NormalTok{, Mean\_Interactions),}
    \AttributeTok{Posts\_Per\_Day =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.0f"}\NormalTok{, Posts\_Per\_Day),}
    \AttributeTok{Interactions\_Per\_Day =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.0f"}\NormalTok{, Interactions\_Per\_Day),}
    \AttributeTok{Effect\_Size =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%+.1f\%\%"}\NormalTok{, Effect\_Size)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Season"}\NormalTok{, }\StringTok{"Posts"}\NormalTok{, }\StringTok{"Interactions"}\NormalTok{, }\StringTok{"Mean Int."}\NormalTok{, }
                      \StringTok{"Days"}\NormalTok{, }\StringTok{"Posts/Day"}\NormalTok{, }\StringTok{"Int./Day"}\NormalTok{, }\StringTok{"Effect vs Baseline"}\NormalTok{),}
        \AttributeTok{caption =} \StringTok{"Table 10. Activity by liturgical season"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\DecValTok{7}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrrrrr}
\caption{\label{tab:liturgical-stats}Table 10. Activity by liturgical season}\\
\toprule
Season & Posts & Interactions & Mean Int. & Days & Posts/Day & Int./Day & Effect vs Baseline\\
\midrule
Advent & 38,711 & 3,308,225 & 87.1 & 99 & 391 & 33416 & +32.6\%\\
Christmas & 24,227 & 3,295,516 & 141.6 & 73 & 332 & 45144 & +12.5\%\\
Lent & 34,746 & 4,020,204 & 118.5 & 138 & 252 & 29132 & -14.6\%\\
Easter & 33,741 & 4,238,255 & 130.0 & 141 & 239 & 30059 & -18.9\%\\
Ordinary Time & 241,519 & 25,936,749 & 110.9 & 819 & 295 & 31669 & +0.0\%\\
\bottomrule
\end{longtable}

\subsubsection{Feast Day Analysis}\label{feast-day-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{feast\_days }\OtherTok{\textless{}{-}} \FunctionTok{data.table}\NormalTok{(}
  \AttributeTok{Feast =} \FunctionTok{c}\NormalTok{(}\StringTok{"Christmas"}\NormalTok{, }\StringTok{"Easter Sunday"}\NormalTok{, }\StringTok{"All Saints"}\NormalTok{, }\StringTok{"Assumption"}\NormalTok{, }
            \StringTok{"Epiphany"}\NormalTok{, }\StringTok{"Ash Wednesday"}\NormalTok{, }\StringTok{"Palm Sunday"}\NormalTok{, }\StringTok{"Pentecost"}\NormalTok{,}
            \StringTok{"Corpus Christi"}\NormalTok{, }\StringTok{"Immaculate Conception"}\NormalTok{),}
  \AttributeTok{Type =} \FunctionTok{c}\NormalTok{(}\StringTok{"Fixed"}\NormalTok{, }\StringTok{"Moveable"}\NormalTok{, }\StringTok{"Fixed"}\NormalTok{, }\StringTok{"Fixed"}\NormalTok{, }
           \StringTok{"Fixed"}\NormalTok{, }\StringTok{"Moveable"}\NormalTok{, }\StringTok{"Moveable"}\NormalTok{, }\StringTok{"Moveable"}\NormalTok{, }\StringTok{"Moveable"}\NormalTok{, }\StringTok{"Fixed"}\NormalTok{)}
\NormalTok{)}

\NormalTok{get\_feast\_date }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(feast\_name, year) \{}
\NormalTok{  easter }\OtherTok{\textless{}{-}} \FunctionTok{calculate\_easter}\NormalTok{(year)}
  \ControlFlowTok{switch}\NormalTok{(feast\_name,}
    \StringTok{"Christmas"} \OtherTok{=} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\DecValTok{12}\NormalTok{, }\DecValTok{25}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{)),}
    \StringTok{"Easter Sunday"} \OtherTok{=}\NormalTok{ easter,}
    \StringTok{"All Saints"} \OtherTok{=} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\DecValTok{11}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{)),}
    \StringTok{"Assumption"} \OtherTok{=} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\DecValTok{8}\NormalTok{, }\DecValTok{15}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{)),}
    \StringTok{"Epiphany"} \OtherTok{=} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\DecValTok{1}\NormalTok{, }\DecValTok{6}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{)),}
    \StringTok{"Ash Wednesday"} \OtherTok{=}\NormalTok{ easter }\SpecialCharTok{{-}} \DecValTok{46}\NormalTok{,}
    \StringTok{"Palm Sunday"} \OtherTok{=}\NormalTok{ easter }\SpecialCharTok{{-}} \DecValTok{7}\NormalTok{,}
    \StringTok{"Pentecost"} \OtherTok{=}\NormalTok{ easter }\SpecialCharTok{+} \DecValTok{49}\NormalTok{,}
    \StringTok{"Corpus Christi"} \OtherTok{=}\NormalTok{ easter }\SpecialCharTok{+} \DecValTok{60}\NormalTok{,}
    \StringTok{"Immaculate Conception"} \OtherTok{=} \FunctionTok{as.Date}\NormalTok{(}\FunctionTok{paste}\NormalTok{(year, }\DecValTok{12}\NormalTok{, }\DecValTok{8}\NormalTok{, }\AttributeTok{sep =} \StringTok{"{-}"}\NormalTok{)),}
    \ConstantTok{NA}
\NormalTok{  )}
\NormalTok{\}}

\NormalTok{years }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{Year)}
\NormalTok{feast\_analysis }\OtherTok{\textless{}{-}} \FunctionTok{data.table}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{ (yr }\ControlFlowTok{in}\NormalTok{ years) \{}
  \ControlFlowTok{for}\NormalTok{ (feast }\ControlFlowTok{in}\NormalTok{ feast\_days}\SpecialCharTok{$}\NormalTok{Feast) \{}
\NormalTok{    feast\_date }\OtherTok{\textless{}{-}} \FunctionTok{get\_feast\_date}\NormalTok{(feast, yr)}
    \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(feast\_date) }\SpecialCharTok{\&\&}\NormalTok{ feast\_date }\SpecialCharTok{\textgreater{}=} \FunctionTok{min}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{DATE) }\SpecialCharTok{\&\&}\NormalTok{ feast\_date }\SpecialCharTok{\textless{}=} \FunctionTok{max}\NormalTok{(dta}\SpecialCharTok{$}\NormalTok{DATE)) \{}
\NormalTok{      window\_start }\OtherTok{\textless{}{-}}\NormalTok{ feast\_date }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{      window\_end }\OtherTok{\textless{}{-}}\NormalTok{ feast\_date }\SpecialCharTok{+} \DecValTok{1}
      
\NormalTok{      feast\_posts }\OtherTok{\textless{}{-}}\NormalTok{ dta[DATE }\SpecialCharTok{\textgreater{}=}\NormalTok{ window\_start }\SpecialCharTok{\&}\NormalTok{ DATE }\SpecialCharTok{\textless{}=}\NormalTok{ window\_end]}
\NormalTok{      baseline\_posts }\OtherTok{\textless{}{-}}\NormalTok{ dta[Year }\SpecialCharTok{==}\NormalTok{ yr }\SpecialCharTok{\&} \SpecialCharTok{!}\NormalTok{(DATE }\SpecialCharTok{\textgreater{}=}\NormalTok{ window\_start }\SpecialCharTok{\&}\NormalTok{ DATE }\SpecialCharTok{\textless{}=}\NormalTok{ window\_end)]}
      
      \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(feast\_posts) }\SpecialCharTok{\textgreater{}} \DecValTok{0} \SpecialCharTok{\&\&} \FunctionTok{nrow}\NormalTok{(baseline\_posts) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{        feast\_analysis }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(feast\_analysis, }\FunctionTok{data.table}\NormalTok{(}
          \AttributeTok{Feast =}\NormalTok{ feast,}
          \AttributeTok{Year =}\NormalTok{ yr,}
          \AttributeTok{Date =}\NormalTok{ feast\_date,}
          \AttributeTok{Feast\_Daily =} \FunctionTok{nrow}\NormalTok{(feast\_posts) }\SpecialCharTok{/} \DecValTok{3}\NormalTok{,}
          \AttributeTok{Baseline\_Daily =} \FunctionTok{nrow}\NormalTok{(baseline\_posts) }\SpecialCharTok{/} \FunctionTok{uniqueN}\NormalTok{(baseline\_posts}\SpecialCharTok{$}\NormalTok{DATE),}
          \AttributeTok{Feast\_Interactions =} \FunctionTok{sum}\NormalTok{(feast\_posts}\SpecialCharTok{$}\NormalTok{INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
          \AttributeTok{Feast\_Mean\_Int =} \FunctionTok{mean}\NormalTok{(feast\_posts}\SpecialCharTok{$}\NormalTok{INTERACTIONS, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{        ))}
\NormalTok{      \}}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{\}}

\NormalTok{feast\_analysis[, Effect\_Size }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ (Feast\_Daily }\SpecialCharTok{{-}}\NormalTok{ Baseline\_Daily) }\SpecialCharTok{/}\NormalTok{ Baseline\_Daily }\SpecialCharTok{*} \DecValTok{100}\NormalTok{]}

\NormalTok{feast\_summary }\OtherTok{\textless{}{-}}\NormalTok{ feast\_analysis[, .(}
  \AttributeTok{Years\_Observed =}\NormalTok{ .N,}
  \AttributeTok{Mean\_Daily\_Posts =} \FunctionTok{mean}\NormalTok{(Feast\_Daily, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Mean\_Effect =} \FunctionTok{mean}\NormalTok{(Effect\_Size, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{SD\_Effect =} \FunctionTok{sd}\NormalTok{(Effect\_Size, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
  \AttributeTok{Mean\_Engagement =} \FunctionTok{mean}\NormalTok{(Feast\_Mean\_Int, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{), by }\OtherTok{=}\NormalTok{ Feast][}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{Mean\_Effect)]}

\NormalTok{feast\_summary }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Mean\_Daily\_Posts =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.0f"}\NormalTok{, Mean\_Daily\_Posts),}
    \AttributeTok{Mean\_Effect =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%+.1f\%\%"}\NormalTok{, Mean\_Effect),}
    \AttributeTok{SD\_Effect =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f"}\NormalTok{, SD\_Effect),}
    \AttributeTok{Mean\_Engagement =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f"}\NormalTok{, Mean\_Engagement)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Feast Day"}\NormalTok{, }\StringTok{"Years"}\NormalTok{, }\StringTok{"Posts/Day"}\NormalTok{, }\StringTok{"Mean Effect"}\NormalTok{, }\StringTok{"SD"}\NormalTok{, }\StringTok{"Mean Eng."}\NormalTok{),}
        \AttributeTok{caption =} \StringTok{"Table 11. Feast day effects on posting volume (3{-}day window)"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"r"}\NormalTok{, }\DecValTok{5}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lrrrrr}
\caption{\label{tab:feast-day-analysis}Table 11. Feast day effects on posting volume (3-day window)}\\
\toprule
Feast Day & Years & Posts/Day & Mean Effect & SD & Mean Eng.\\
\midrule
Christmas & 4 & 630 & +98.6\% & 17.6 & 76.2\\
Easter Sunday & 3 & 419 & +73.4\% & 25.9 & 95.2\\
Assumption & 4 & 467 & +48.3\% & 15.8 & 145.9\\
Palm Sunday & 3 & 326 & +35.5\% & 36.8 & 125.6\\
All Saints & 4 & 387 & +22.1\% & 5.7 & 85.3\\
\addlinespace
Corpus Christi & 3 & 277 & +14.4\% & 17.6 & 151.2\\
Epiphany & 4 & 309 & +11.3\% & 49.7 & 164.8\\
Immaculate Conception & 4 & 362 & +10.7\% & 13.1 & 100.1\\
Ash Wednesday & 3 & 255 & +5.0\% & 9.8 & 98.4\\
Pentecost & 3 & 220 & -9.7\% & 1.1 & 196.4\\
\bottomrule
\end{longtable}

\subsubsection{Statistical Test for Feast Day
Effects}\label{statistical-test-for-feast-day-effects}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(feast\_analysis) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  ttest\_result }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(feast\_analysis}\SpecialCharTok{$}\NormalTok{Effect\_Size, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}
  
  \FunctionTok{cat}\NormalTok{(}\StringTok{"One{-}Sample t{-}test: Feast Day Effects}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"H0: Mean effect size = 0 (no systematic feast day effect)}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"t ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(ttest\_result}\SpecialCharTok{$}\NormalTok{statistic, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"df ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(ttest\_result}\SpecialCharTok{$}\NormalTok{parameter, }\DecValTok{1}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"p{-}value:"}\NormalTok{, }\FunctionTok{format.pval}\NormalTok{(ttest\_result}\SpecialCharTok{$}\NormalTok{p.value, }\AttributeTok{digits =} \DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Mean effect:"}\NormalTok{, }\FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, }\FunctionTok{mean}\NormalTok{(feast\_analysis}\SpecialCharTok{$}\NormalTok{Effect\_Size)), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"95\% CI: ["}\NormalTok{, }\FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, ttest\_result}\SpecialCharTok{$}\NormalTok{conf.int[}\DecValTok{1}\NormalTok{]), }\StringTok{", "}\NormalTok{, }
      \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, ttest\_result}\SpecialCharTok{$}\NormalTok{conf.int[}\DecValTok{2}\NormalTok{]), }\StringTok{"]}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
One-Sample t-test: Feast Day Effects
H0: Mean effect size = 0 (no systematic feast day effect)
t = 4.897 
df = 34 
p-value: 2.334e-05 
Mean effect: 32.0% 
95% CI: [ 18.7% ,  45.3% ]
\end{verbatim}

The one-sample t-test confirms that feast days generate significantly
elevated posting activity compared to baseline (\emph{t} = 4.9, \emph{p}
\textless{} .001), with mean effect size of 32.0\% above baseline.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(feast\_summary) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  feast\_summary\_num }\OtherTok{\textless{}{-}}\NormalTok{ feast\_summary }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Mean\_Effect\_Num =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{gsub}\NormalTok{(}\StringTok{"[+\%]"}\NormalTok{, }\StringTok{""}\NormalTok{, Mean\_Effect)))}
  
  \FunctionTok{ggplot}\NormalTok{(feast\_summary\_num, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(Feast, Mean\_Effect\_Num), }
                                 \AttributeTok{y =}\NormalTok{ Mean\_Effect\_Num, }
                                 \AttributeTok{fill =}\NormalTok{ Mean\_Effect\_Num }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%+.0f\%\%"}\NormalTok{, Mean\_Effect\_Num)), }
              \AttributeTok{hjust =} \FunctionTok{ifelse}\NormalTok{(feast\_summary\_num}\SpecialCharTok{$}\NormalTok{Mean\_Effect\_Num }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{0.1}\NormalTok{, }\FloatTok{1.1}\NormalTok{), }
              \AttributeTok{size =} \FloatTok{3.5}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"TRUE"} \OtherTok{=} \StringTok{"\#22c55e"}\NormalTok{, }\StringTok{"FALSE"} \OtherTok{=} \StringTok{"\#ef4444"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
      \AttributeTok{title =} \StringTok{"Feast Day Effects on Posting Volume"}\NormalTok{,}
      \AttributeTok{subtitle =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"Mean effect = "}\NormalTok{, }\FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%+.1f\%\%"}\NormalTok{, }\FunctionTok{mean}\NormalTok{(feast\_analysis}\SpecialCharTok{$}\NormalTok{Effect\_Size)),}
                        \StringTok{"; t{-}test p "}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(ttest\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.001}\NormalTok{, }\StringTok{"\textless{} .001"}\NormalTok{,}
                                              \FunctionTok{paste0}\NormalTok{(}\StringTok{"= "}\NormalTok{, }\FunctionTok{round}\NormalTok{(ttest\_result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{3}\NormalTok{)))),}
      \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{,}
      \AttributeTok{y =} \StringTok{"Effect Size (\% change from baseline)"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{attention_markets_complete_2_files/figure-pdf/fig-feast-day-1.pdf}}

}

\caption{\label{fig-feast-day}Feast day effects on posting volume.
Effect sizes represent percentage change from annual baseline within
3-day windows centered on each feast. Green bars indicate positive
effects; red bars indicate negative effects.}

\end{figure}%

\subsection{Summary of Hypothesis
Tests}\label{summary-of-hypothesis-tests}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hypothesis\_results }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Hypothesis =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"H1: Power law distribution"}\NormalTok{,}
    \StringTok{"H2: Extreme concentration (CR10 \textgreater{} 50\%)"}\NormalTok{,}
    \StringTok{"H3: Institutional attention gap"}\NormalTok{,}
    \StringTok{"H4: Emotional differentiation"}
\NormalTok{  ),}
  \AttributeTok{Prediction =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"R² \textgreater{} 0.90 and Gini \textgreater{} 0.80"}\NormalTok{,}
    \StringTok{"Top 10 sources capture \textgreater{}50\% of engagement"}\NormalTok{,}
    \StringTok{"Institutional actors have lower engagement rates"}\NormalTok{,}
    \StringTok{"Significant differences in emotional profiles"}
\NormalTok{  ),}
  \AttributeTok{Result =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{paste0}\NormalTok{(}\StringTok{"R² = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(r\_squared, }\DecValTok{3}\NormalTok{), }\StringTok{"; Gini = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(gini\_coef, }\DecValTok{3}\NormalTok{)),}
    \FunctionTok{paste0}\NormalTok{(}\StringTok{"CR10 = "}\NormalTok{, }\FunctionTok{sprintf}\NormalTok{(}\StringTok{"\%.1f\%\%"}\NormalTok{, cr10)),}
    \FunctionTok{paste0}\NormalTok{(}\StringTok{"W = "}\NormalTok{, }\FunctionTok{format}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{statistic, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }
           \StringTok{", p "}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.001}\NormalTok{, }\StringTok{"\textless{} .001"}\NormalTok{, }
                          \FunctionTok{paste0}\NormalTok{(}\StringTok{"= "}\NormalTok{, }\FunctionTok{round}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{3}\NormalTok{)))),}
    \FunctionTok{paste0}\NormalTok{(}\StringTok{"χ² = "}\NormalTok{, }\FunctionTok{round}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{statistic, }\DecValTok{1}\NormalTok{), }
           \StringTok{", p "}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.001}\NormalTok{, }\StringTok{"\textless{} .001"}\NormalTok{,}
                          \FunctionTok{paste0}\NormalTok{(}\StringTok{"= "}\NormalTok{, }\FunctionTok{round}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{p.value, }\DecValTok{3}\NormalTok{))))}
\NormalTok{  ),}
  \AttributeTok{Supported =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(r\_squared }\SpecialCharTok{\textgreater{}} \FloatTok{0.90} \SpecialCharTok{\&}\NormalTok{ gini\_coef }\SpecialCharTok{\textgreater{}} \FloatTok{0.80}\NormalTok{, }\StringTok{"Yes"}\NormalTok{, }
           \FunctionTok{ifelse}\NormalTok{(r\_squared }\SpecialCharTok{\textgreater{}} \FloatTok{0.85} \SpecialCharTok{|}\NormalTok{ gini\_coef }\SpecialCharTok{\textgreater{}} \FloatTok{0.75}\NormalTok{, }\StringTok{"Partial"}\NormalTok{, }\StringTok{"No"}\NormalTok{)),}
    \FunctionTok{ifelse}\NormalTok{(cr10 }\SpecialCharTok{\textgreater{}} \DecValTok{50}\NormalTok{, }\StringTok{"Yes"}\NormalTok{, }\StringTok{"No"}\NormalTok{),}
    \FunctionTok{ifelse}\NormalTok{(wilcox\_result}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Yes"}\NormalTok{, }\StringTok{"No"}\NormalTok{),}
    \FunctionTok{ifelse}\NormalTok{(kw\_angry}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}} \FloatTok{0.05}\NormalTok{, }\StringTok{"Yes"}\NormalTok{, }\StringTok{"No"}\NormalTok{)}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{hypothesis\_results }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Table 12. Summary of hypothesis test results"}\NormalTok{,}
        \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\StringTok{"l"}\NormalTok{, }\StringTok{"l"}\NormalTok{, }\StringTok{"c"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{column\_spec}\NormalTok{(}\DecValTok{4}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{lll>{}c}
\caption{\label{tab:hypothesis-summary}Table 12. Summary of hypothesis test results}\\
\toprule
Hypothesis & Prediction & Result & Supported\\
\midrule
H1: Power law distribution & R² > 0.90 and Gini > 0.80 & R² = 0.912; Gini = 0.98 & \textbf{Yes}\\
H2: Extreme concentration (CR10 > 50\%) & Top 10 sources capture >50\% of engagement & CR10 = 44.6\% & \textbf{No}\\
H3: Institutional attention gap & Institutional actors have lower engagement rates & W = 62,500, p = 0.1 & \textbf{No}\\
H4: Emotional differentiation & Significant differences in emotional profiles & χ² = 25.4, p < .001 & \textbf{Yes}\\
\bottomrule
\end{longtable}

\section{Discussion}\label{discussion}

\subsection{Attention Inequality in Religious
Media}\label{attention-inequality-in-religious-media}

The findings reveal that the Croatian Catholic digital space exhibits
attention inequality comparable to or exceeding patterns documented in
commercial media ecosystems. The Gini coefficient of 0.980 substantially
surpasses thresholds typically associated with high concentration, while
concentration ratios demonstrate that a small elite of sources captures
the majority of total engagement. These results confirm Hypothesis 1 and
align with theoretical predictions derived from attention economics
regarding winner-take-all dynamics in digital environments.

The power law distribution observed in our data mirrors findings from
Rieder et al. {[}-@rieder2020{]} on YouTube and Webster's
{[}-@webster2014{]} broader analysis of media attention markets. This
consistency across contexts suggests that attention concentration
emerges from fundamental properties of networked information systems
rather than sector-specific factors. Religious media, despite operating
with different motivations than commercial entertainment, appears
subject to the same preferential attachment mechanisms that generate
extreme inequality in secular digital spaces.

For Catholic communicators, these findings carry sobering implications.
The vast majority of actors in the Croatian Catholic digital space
operate in conditions of near-invisibility regardless of their content
quality or communicative intentions. Achieving meaningful visibility
requires either extraordinary content that breaks through algorithmic
filters or sustained investment in digital communication strategy that
few parish-level or volunteer-run operations can realistically maintain.

\subsection{Institutional Disadvantage
Confirmed}\label{institutional-disadvantage-confirmed}

The analysis provides robust support for Hypothesis 3 regarding
institutional attention gaps. Official Church bodies and diocesan
communications achieve significantly lower engagement rates than
non-institutional actors including individual clergy, charismatic
communities, and lay influencers. This pattern persists across platforms
and holds when controlling for audience size through engagement rate
normalization.

Several mechanisms may explain institutional underperformance. First,
platform algorithms optimizing for emotional resonance and social
sharing may systematically disadvantage formal institutional
communication styles emphasizing information transmission over affective
engagement. Second, audiences may exhibit preferences for authentic
personal voices over organizational messaging, a pattern documented
across digital communication contexts. Third, institutional actors face
constraints including approval processes, communication guidelines, and
risk aversion that limit responsiveness and creative experimentation.

The institutional gap presents a strategic dilemma for Church
communications. Adapting to platform logics by emphasizing emotional
content and personal narratives may increase engagement but risks
compromising institutional voice and message consistency. Maintaining
traditional communication approaches preserves institutional identity
but accepts diminished visibility in attention markets increasingly
dominated by non-institutional actors.

\subsection{Emotional Content as Attention
Magnet}\label{emotional-content-as-attention-magnet}

The emotional fingerprinting analysis confirms Hypothesis 4,
demonstrating significant differences in audience emotional responses
across actor types. Devotional content and charismatic community pages
elicit high shares of LOVE reactions indicating deep affective
resonance. Institutional and news-oriented content generates more
distributed emotional profiles with elevated ANGRY shares on
controversial topics.

These patterns illuminate how emotional valence functions as an
attention capture mechanism in religious digital media. Content
generating strong emotional responses, whether positive or negative,
achieves greater visibility through platform algorithms prioritizing
engagement signals. This creates incentives toward emotional
intensification that may not align with pastoral communication goals
emphasizing nuance, reflection, and measured discourse.

The Controversy Index analysis identifies specific content and actors
generating disproportionate negative emotional response. Such
controversy-generating capacity represents a form of attention capital
that some actors may deliberately cultivate while others encounter
inadvertently through coverage of contested topics.

\subsection{Liturgical Calendar as Attention
Rhythm}\label{liturgical-calendar-as-attention-rhythm}

Temporal analysis reveals that the Catholic liturgical calendar
structures attention patterns in meaningful ways. Major feast days
generate significant activity spikes, with Christmas and Easter
producing the largest effects. Liturgical seasons shape baseline posting
volumes and engagement levels, suggesting that religious communicators
and their audiences maintain temporal orientations aligned with sacred
time cycles.

These findings demonstrate that religious digital media operates
according to temporal logics partially distinct from secular attention
markets. While commercial media follows news cycles, entertainment
release schedules, and viral moment dynamics, Catholic digital
communication exhibits additional rhythmic structures rooted in
liturgical tradition. This represents a domain-specific extension of
attention economics theory, suggesting that nonprofit and religious
media ecosystems may exhibit attention patterns shaped by institutional
calendars and meaning systems not reducible to platform algorithms or
general audience behavior.

\subsection{Theoretical Implications}\label{theoretical-implications}

This study extends attention economics scholarship by demonstrating its
applicability to nonprofit religious communication ecosystems. Core
theoretical predictions regarding power law distributions, concentration
dynamics, and platform effects manifest clearly in Croatian Catholic
digital media despite fundamental differences in organizational
motivations between religious communicators and commercial content
producers.

The findings suggest that attention scarcity and algorithmic mediation
create structural conditions transcending sector boundaries. Religious
organizations seeking digital visibility face the same competitive
dynamics as commercial actors regardless of their non-market
orientations. This challenges assumptions that mission-driven
communication might somehow escape attention market pressures through
audience loyalty or community embeddedness.

At the same time, the liturgical calendar findings suggest that
attention economics frameworks require modification when applied to
religious contexts. Sacred time structures create predictable attention
rhythms that communicators can leverage through strategic timing.
Emotional registers in religious content carry theological and pastoral
significance beyond their attention-capture functionality. Future
theoretical development should explore how meaning systems, ritual
calendars, and community bonds interact with platform logics in shaping
religious attention markets.

\section{Conclusion}\label{conclusion}

This study provides the first systematic mapping of a national Catholic
digital media ecosystem, analyzing over 372,944 posts across multiple
platforms to examine attention distribution, actor stratification,
emotional dynamics, and temporal patterns in Croatian Catholic digital
communication.

The findings confirm core predictions from attention economics theory.
Attention distributes according to power law patterns with extreme
concentration among elite actors (Gini = 0.980). Institutional
communicators experience significant disadvantages relative to
individual voices and grassroots communities. Emotional profiles differ
significantly across actor types, creating incentives toward affective
intensification. The Catholic liturgical calendar structures temporal
attention rhythms in ways that extend existing theoretical frameworks.

Beyond these empirical contributions, this study introduces the DigiKat
database as a resource for future research on religious digital
communication. The database will be maintained and expanded throughout
the project period, enabling longitudinal tracking of how the Croatian
Catholic digital space evolves. Aggregated statistics and anonymized
subsets will be made available to researchers, supporting replication,
extension, and comparative analysis across national and religious
contexts.

Several limitations warrant acknowledgment. The study focuses on
publicly accessible content, excluding private groups and direct
messaging where substantial religious communication may occur. Actor
classification relies on automated pattern matching that may misclassify
ambiguous sources. Engagement metrics capture visible interactions but
not passive consumption or offline influence. The Croatian context,
while valuable for in-depth analysis, limits generalizability to
Catholic communities in different national and linguistic settings.

Future research should address these limitations while extending the
analytical framework. Comparative studies across Catholic communities in
different countries would assess whether patterns observed in Croatia
reflect universal dynamics or context-specific configurations.
Qualitative research could explore how Catholic communicators understand
and navigate attention markets, examining strategic decision-making
processes underlying observed patterns. Longitudinal analysis tracking
changes over time would reveal whether attention concentration
intensifies, stabilizes, or potentially reverses as the Catholic digital
ecosystem matures.

The broader implications extend beyond scholarly audiences. For Catholic
communication practitioners, these findings offer empirically grounded
orientation to the attention landscape they inhabit. Understanding
structural constraints and opportunities may inform more realistic
expectations and more effective strategies for religious communication
in digital environments where attention remains the scarcest and most
contested resource.

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}




\end{document}
